// Code generated by ent, DO NOT EDIT.

package notebookshare

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the notebookshare type in the database.
	Label = "notebook_share"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNotebookID holds the string denoting the notebook_id field in the database.
	FieldNotebookID = "notebook_id"
	// FieldSharedWithUserID holds the string denoting the shared_with_user_id field in the database.
	FieldSharedWithUserID = "shared_with_user_id"
	// FieldPermission holds the string denoting the permission field in the database.
	FieldPermission = "permission"
	// FieldSharedByUserID holds the string denoting the shared_by_user_id field in the database.
	FieldSharedByUserID = "shared_by_user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeNotebook holds the string denoting the notebook edge name in mutations.
	EdgeNotebook = "notebook"
	// EdgeSharedWith holds the string denoting the shared_with edge name in mutations.
	EdgeSharedWith = "shared_with"
	// Table holds the table name of the notebookshare in the database.
	Table = "notebook_shares"
	// NotebookTable is the table that holds the notebook relation/edge.
	NotebookTable = "notebook_shares"
	// NotebookInverseTable is the table name for the Notebook entity.
	// It exists in this package in order to avoid circular dependency with the "notebook" package.
	NotebookInverseTable = "notebooks"
	// NotebookColumn is the table column denoting the notebook relation/edge.
	NotebookColumn = "notebook_id"
	// SharedWithTable is the table that holds the shared_with relation/edge.
	SharedWithTable = "notebook_shares"
	// SharedWithInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SharedWithInverseTable = "users"
	// SharedWithColumn is the table column denoting the shared_with relation/edge.
	SharedWithColumn = "shared_with_user_id"
)

// Columns holds all SQL columns for notebookshare fields.
var Columns = []string{
	FieldID,
	FieldNotebookID,
	FieldSharedWithUserID,
	FieldPermission,
	FieldSharedByUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Permission defines the type for the "permission" enum field.
type Permission string

// PermissionView is the default value of the Permission enum.
const DefaultPermission = PermissionView

// Permission values.
const (
	PermissionView  Permission = "view"
	PermissionEdit  Permission = "edit"
	PermissionAdmin Permission = "admin"
)

func (pe Permission) String() string {
	return string(pe)
}

// PermissionValidator is a validator for the "permission" field enum values. It is called by the builders before save.
func PermissionValidator(pe Permission) error {
	switch pe {
	case PermissionView, PermissionEdit, PermissionAdmin:
		return nil
	default:
		return fmt.Errorf("notebookshare: invalid enum value for permission field: %q", pe)
	}
}

// OrderOption defines the ordering options for the NotebookShare queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNotebookID orders the results by the notebook_id field.
func ByNotebookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotebookID, opts...).ToFunc()
}

// BySharedWithUserID orders the results by the shared_with_user_id field.
func BySharedWithUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharedWithUserID, opts...).ToFunc()
}

// ByPermission orders the results by the permission field.
func ByPermission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermission, opts...).ToFunc()
}

// BySharedByUserID orders the results by the shared_by_user_id field.
func BySharedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharedByUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByNotebookField orders the results by notebook field.
func ByNotebookField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotebookStep(), sql.OrderByField(field, opts...))
	}
}

// BySharedWithField orders the results by shared_with field.
func BySharedWithField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSharedWithStep(), sql.OrderByField(field, opts...))
	}
}
func newNotebookStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotebookInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NotebookTable, NotebookColumn),
	)
}
func newSharedWithStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SharedWithInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SharedWithTable, SharedWithColumn),
	)
}
