// Code generated by ent, DO NOT EDIT.

package notebookshare

import (
	"gladiator/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLTE(FieldID, id))
}

// NotebookID applies equality check predicate on the "notebook_id" field. It's identical to NotebookIDEQ.
func NotebookID(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldNotebookID, v))
}

// SharedWithUserID applies equality check predicate on the "shared_with_user_id" field. It's identical to SharedWithUserIDEQ.
func SharedWithUserID(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldSharedWithUserID, v))
}

// SharedByUserID applies equality check predicate on the "shared_by_user_id" field. It's identical to SharedByUserIDEQ.
func SharedByUserID(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldSharedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldCreatedAt, v))
}

// NotebookIDEQ applies the EQ predicate on the "notebook_id" field.
func NotebookIDEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldNotebookID, v))
}

// NotebookIDNEQ applies the NEQ predicate on the "notebook_id" field.
func NotebookIDNEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldNotebookID, v))
}

// NotebookIDIn applies the In predicate on the "notebook_id" field.
func NotebookIDIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldNotebookID, vs...))
}

// NotebookIDNotIn applies the NotIn predicate on the "notebook_id" field.
func NotebookIDNotIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldNotebookID, vs...))
}

// SharedWithUserIDEQ applies the EQ predicate on the "shared_with_user_id" field.
func SharedWithUserIDEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldSharedWithUserID, v))
}

// SharedWithUserIDNEQ applies the NEQ predicate on the "shared_with_user_id" field.
func SharedWithUserIDNEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldSharedWithUserID, v))
}

// SharedWithUserIDIn applies the In predicate on the "shared_with_user_id" field.
func SharedWithUserIDIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldSharedWithUserID, vs...))
}

// SharedWithUserIDNotIn applies the NotIn predicate on the "shared_with_user_id" field.
func SharedWithUserIDNotIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldSharedWithUserID, vs...))
}

// PermissionEQ applies the EQ predicate on the "permission" field.
func PermissionEQ(v Permission) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldPermission, v))
}

// PermissionNEQ applies the NEQ predicate on the "permission" field.
func PermissionNEQ(v Permission) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldPermission, v))
}

// PermissionIn applies the In predicate on the "permission" field.
func PermissionIn(vs ...Permission) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldPermission, vs...))
}

// PermissionNotIn applies the NotIn predicate on the "permission" field.
func PermissionNotIn(vs ...Permission) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldPermission, vs...))
}

// SharedByUserIDEQ applies the EQ predicate on the "shared_by_user_id" field.
func SharedByUserIDEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldSharedByUserID, v))
}

// SharedByUserIDNEQ applies the NEQ predicate on the "shared_by_user_id" field.
func SharedByUserIDNEQ(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldSharedByUserID, v))
}

// SharedByUserIDIn applies the In predicate on the "shared_by_user_id" field.
func SharedByUserIDIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldSharedByUserID, vs...))
}

// SharedByUserIDNotIn applies the NotIn predicate on the "shared_by_user_id" field.
func SharedByUserIDNotIn(vs ...uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldSharedByUserID, vs...))
}

// SharedByUserIDGT applies the GT predicate on the "shared_by_user_id" field.
func SharedByUserIDGT(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGT(FieldSharedByUserID, v))
}

// SharedByUserIDGTE applies the GTE predicate on the "shared_by_user_id" field.
func SharedByUserIDGTE(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGTE(FieldSharedByUserID, v))
}

// SharedByUserIDLT applies the LT predicate on the "shared_by_user_id" field.
func SharedByUserIDLT(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLT(FieldSharedByUserID, v))
}

// SharedByUserIDLTE applies the LTE predicate on the "shared_by_user_id" field.
func SharedByUserIDLTE(v uuid.UUID) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLTE(FieldSharedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotebookShare {
	return predicate.NotebookShare(sql.FieldLTE(FieldCreatedAt, v))
}

// HasNotebook applies the HasEdge predicate on the "notebook" edge.
func HasNotebook() predicate.NotebookShare {
	return predicate.NotebookShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NotebookTable, NotebookColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotebookWith applies the HasEdge predicate on the "notebook" edge with a given conditions (other predicates).
func HasNotebookWith(preds ...predicate.Notebook) predicate.NotebookShare {
	return predicate.NotebookShare(func(s *sql.Selector) {
		step := newNotebookStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSharedWith applies the HasEdge predicate on the "shared_with" edge.
func HasSharedWith() predicate.NotebookShare {
	return predicate.NotebookShare(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SharedWithTable, SharedWithColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSharedWithWith applies the HasEdge predicate on the "shared_with" edge with a given conditions (other predicates).
func HasSharedWithWith(preds ...predicate.User) predicate.NotebookShare {
	return predicate.NotebookShare(func(s *sql.Selector) {
		step := newSharedWithStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotebookShare) predicate.NotebookShare {
	return predicate.NotebookShare(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotebookShare) predicate.NotebookShare {
	return predicate.NotebookShare(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotebookShare) predicate.NotebookShare {
	return predicate.NotebookShare(sql.NotPredicates(p))
}
