// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotebooksColumns holds the columns for the "notebooks" table.
	NotebooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeJSON},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_executed_at", Type: field.TypeTime, Nullable: true},
		{Name: "execution_count", Type: field.TypeInt, Default: 0},
		{Name: "owner_id", Type: field.TypeUUID},
	}
	// NotebooksTable holds the schema information for the "notebooks" table.
	NotebooksTable = &schema.Table{
		Name:       "notebooks",
		Columns:    NotebooksColumns,
		PrimaryKey: []*schema.Column{NotebooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notebooks_users_notebooks",
				Columns:    []*schema.Column{NotebooksColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notebook_owner_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{NotebooksColumns[9], NotebooksColumns[5]},
			},
			{
				Name:    "notebook_owner_id_updated_at",
				Unique:  false,
				Columns: []*schema.Column{NotebooksColumns[9], NotebooksColumns[6]},
			},
			{
				Name:    "notebook_is_public_created_at",
				Unique:  false,
				Columns: []*schema.Column{NotebooksColumns[4], NotebooksColumns[5]},
			},
			{
				Name:    "notebook_updated_at",
				Unique:  false,
				Columns: []*schema.Column{NotebooksColumns[6]},
			},
		},
	}
	// NotebookSharesColumns holds the columns for the "notebook_shares" table.
	NotebookSharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "permission", Type: field.TypeEnum, Enums: []string{"view", "edit", "admin"}, Default: "view"},
		{Name: "shared_by_user_id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "notebook_id", Type: field.TypeUUID},
		{Name: "shared_with_user_id", Type: field.TypeUUID},
	}
	// NotebookSharesTable holds the schema information for the "notebook_shares" table.
	NotebookSharesTable = &schema.Table{
		Name:       "notebook_shares",
		Columns:    NotebookSharesColumns,
		PrimaryKey: []*schema.Column{NotebookSharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notebook_shares_notebooks_shares",
				Columns:    []*schema.Column{NotebookSharesColumns[4]},
				RefColumns: []*schema.Column{NotebooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "notebook_shares_users_shared_notebooks",
				Columns:    []*schema.Column{NotebookSharesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notebookshare_notebook_id_shared_with_user_id",
				Unique:  true,
				Columns: []*schema.Column{NotebookSharesColumns[4], NotebookSharesColumns[5]},
			},
			{
				Name:    "notebookshare_notebook_id",
				Unique:  false,
				Columns: []*schema.Column{NotebookSharesColumns[4]},
			},
			{
				Name:    "notebookshare_shared_with_user_id",
				Unique:  false,
				Columns: []*schema.Column{NotebookSharesColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotebooksTable,
		NotebookSharesTable,
		UsersTable,
	}
)

func init() {
	NotebooksTable.ForeignKeys[0].RefTable = UsersTable
	NotebookSharesTable.ForeignKeys[0].RefTable = NotebooksTable
	NotebookSharesTable.ForeignKeys[1].RefTable = UsersTable
}
