// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"gladiator/ent/migrate"

	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Notebook is the client for interacting with the Notebook builders.
	Notebook *NotebookClient
	// NotebookShare is the client for interacting with the NotebookShare builders.
	NotebookShare *NotebookShareClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Notebook = NewNotebookClient(c.config)
	c.NotebookShare = NewNotebookShareClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Notebook:      NewNotebookClient(cfg),
		NotebookShare: NewNotebookShareClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Notebook:      NewNotebookClient(cfg),
		NotebookShare: NewNotebookShareClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Notebook.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Notebook.Use(hooks...)
	c.NotebookShare.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Notebook.Intercept(interceptors...)
	c.NotebookShare.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *NotebookMutation:
		return c.Notebook.mutate(ctx, m)
	case *NotebookShareMutation:
		return c.NotebookShare.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// NotebookClient is a client for the Notebook schema.
type NotebookClient struct {
	config
}

// NewNotebookClient returns a client for the Notebook from the given config.
func NewNotebookClient(c config) *NotebookClient {
	return &NotebookClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notebook.Hooks(f(g(h())))`.
func (c *NotebookClient) Use(hooks ...Hook) {
	c.hooks.Notebook = append(c.hooks.Notebook, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notebook.Intercept(f(g(h())))`.
func (c *NotebookClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notebook = append(c.inters.Notebook, interceptors...)
}

// Create returns a builder for creating a Notebook entity.
func (c *NotebookClient) Create() *NotebookCreate {
	mutation := newNotebookMutation(c.config, OpCreate)
	return &NotebookCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notebook entities.
func (c *NotebookClient) CreateBulk(builders ...*NotebookCreate) *NotebookCreateBulk {
	return &NotebookCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotebookClient) MapCreateBulk(slice any, setFunc func(*NotebookCreate, int)) *NotebookCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotebookCreateBulk{err: fmt.Errorf("calling to NotebookClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotebookCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotebookCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notebook.
func (c *NotebookClient) Update() *NotebookUpdate {
	mutation := newNotebookMutation(c.config, OpUpdate)
	return &NotebookUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotebookClient) UpdateOne(n *Notebook) *NotebookUpdateOne {
	mutation := newNotebookMutation(c.config, OpUpdateOne, withNotebook(n))
	return &NotebookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotebookClient) UpdateOneID(id uuid.UUID) *NotebookUpdateOne {
	mutation := newNotebookMutation(c.config, OpUpdateOne, withNotebookID(id))
	return &NotebookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notebook.
func (c *NotebookClient) Delete() *NotebookDelete {
	mutation := newNotebookMutation(c.config, OpDelete)
	return &NotebookDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotebookClient) DeleteOne(n *Notebook) *NotebookDeleteOne {
	return c.DeleteOneID(n.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotebookClient) DeleteOneID(id uuid.UUID) *NotebookDeleteOne {
	builder := c.Delete().Where(notebook.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotebookDeleteOne{builder}
}

// Query returns a query builder for Notebook.
func (c *NotebookClient) Query() *NotebookQuery {
	return &NotebookQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotebook},
		inters: c.Interceptors(),
	}
}

// Get returns a Notebook entity by its id.
func (c *NotebookClient) Get(ctx context.Context, id uuid.UUID) (*Notebook, error) {
	return c.Query().Where(notebook.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotebookClient) GetX(ctx context.Context, id uuid.UUID) *Notebook {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Notebook.
func (c *NotebookClient) QueryOwner(n *Notebook) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := n.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notebook.Table, notebook.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebook.OwnerTable, notebook.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(n.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryShares queries the shares edge of a Notebook.
func (c *NotebookClient) QueryShares(n *Notebook) *NotebookShareQuery {
	query := (&NotebookShareClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := n.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notebook.Table, notebook.FieldID, id),
			sqlgraph.To(notebookshare.Table, notebookshare.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, notebook.SharesTable, notebook.SharesColumn),
		)
		fromV = sqlgraph.Neighbors(n.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotebookClient) Hooks() []Hook {
	return c.hooks.Notebook
}

// Interceptors returns the client interceptors.
func (c *NotebookClient) Interceptors() []Interceptor {
	return c.inters.Notebook
}

func (c *NotebookClient) mutate(ctx context.Context, m *NotebookMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotebookCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotebookUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotebookUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotebookDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notebook mutation op: %q", m.Op())
	}
}

// NotebookShareClient is a client for the NotebookShare schema.
type NotebookShareClient struct {
	config
}

// NewNotebookShareClient returns a client for the NotebookShare from the given config.
func NewNotebookShareClient(c config) *NotebookShareClient {
	return &NotebookShareClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notebookshare.Hooks(f(g(h())))`.
func (c *NotebookShareClient) Use(hooks ...Hook) {
	c.hooks.NotebookShare = append(c.hooks.NotebookShare, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notebookshare.Intercept(f(g(h())))`.
func (c *NotebookShareClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotebookShare = append(c.inters.NotebookShare, interceptors...)
}

// Create returns a builder for creating a NotebookShare entity.
func (c *NotebookShareClient) Create() *NotebookShareCreate {
	mutation := newNotebookShareMutation(c.config, OpCreate)
	return &NotebookShareCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotebookShare entities.
func (c *NotebookShareClient) CreateBulk(builders ...*NotebookShareCreate) *NotebookShareCreateBulk {
	return &NotebookShareCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotebookShareClient) MapCreateBulk(slice any, setFunc func(*NotebookShareCreate, int)) *NotebookShareCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotebookShareCreateBulk{err: fmt.Errorf("calling to NotebookShareClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotebookShareCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotebookShareCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotebookShare.
func (c *NotebookShareClient) Update() *NotebookShareUpdate {
	mutation := newNotebookShareMutation(c.config, OpUpdate)
	return &NotebookShareUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotebookShareClient) UpdateOne(ns *NotebookShare) *NotebookShareUpdateOne {
	mutation := newNotebookShareMutation(c.config, OpUpdateOne, withNotebookShare(ns))
	return &NotebookShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotebookShareClient) UpdateOneID(id uuid.UUID) *NotebookShareUpdateOne {
	mutation := newNotebookShareMutation(c.config, OpUpdateOne, withNotebookShareID(id))
	return &NotebookShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotebookShare.
func (c *NotebookShareClient) Delete() *NotebookShareDelete {
	mutation := newNotebookShareMutation(c.config, OpDelete)
	return &NotebookShareDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotebookShareClient) DeleteOne(ns *NotebookShare) *NotebookShareDeleteOne {
	return c.DeleteOneID(ns.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotebookShareClient) DeleteOneID(id uuid.UUID) *NotebookShareDeleteOne {
	builder := c.Delete().Where(notebookshare.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotebookShareDeleteOne{builder}
}

// Query returns a query builder for NotebookShare.
func (c *NotebookShareClient) Query() *NotebookShareQuery {
	return &NotebookShareQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotebookShare},
		inters: c.Interceptors(),
	}
}

// Get returns a NotebookShare entity by its id.
func (c *NotebookShareClient) Get(ctx context.Context, id uuid.UUID) (*NotebookShare, error) {
	return c.Query().Where(notebookshare.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotebookShareClient) GetX(ctx context.Context, id uuid.UUID) *NotebookShare {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotebook queries the notebook edge of a NotebookShare.
func (c *NotebookShareClient) QueryNotebook(ns *NotebookShare) *NotebookQuery {
	query := (&NotebookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ns.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notebookshare.Table, notebookshare.FieldID, id),
			sqlgraph.To(notebook.Table, notebook.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebookshare.NotebookTable, notebookshare.NotebookColumn),
		)
		fromV = sqlgraph.Neighbors(ns.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySharedWith queries the shared_with edge of a NotebookShare.
func (c *NotebookShareClient) QuerySharedWith(ns *NotebookShare) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ns.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notebookshare.Table, notebookshare.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebookshare.SharedWithTable, notebookshare.SharedWithColumn),
		)
		fromV = sqlgraph.Neighbors(ns.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotebookShareClient) Hooks() []Hook {
	return c.hooks.NotebookShare
}

// Interceptors returns the client interceptors.
func (c *NotebookShareClient) Interceptors() []Interceptor {
	return c.inters.NotebookShare
}

func (c *NotebookShareClient) mutate(ctx context.Context, m *NotebookShareMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotebookShareCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotebookShareUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotebookShareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotebookShareDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotebookShare mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotebooks queries the notebooks edge of a User.
func (c *UserClient) QueryNotebooks(u *User) *NotebookQuery {
	query := (&NotebookClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(notebook.Table, notebook.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.NotebooksTable, user.NotebooksColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySharedNotebooks queries the shared_notebooks edge of a User.
func (c *UserClient) QuerySharedNotebooks(u *User) *NotebookShareQuery {
	query := (&NotebookShareClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(notebookshare.Table, notebookshare.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SharedNotebooksTable, user.SharedNotebooksColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Notebook, NotebookShare, User []ent.Hook
	}
	inters struct {
		Notebook, NotebookShare, User []ent.Interceptor
	}
)
