// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"
	"gladiator/ent/user"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeNotebook      = "Notebook"
	TypeNotebookShare = "NotebookShare"
	TypeUser          = "User"
)

// NotebookMutation represents an operation that mutates the Notebook nodes in the graph.
type NotebookMutation struct {
	config
	op                 Op
	typ                string
	id                 *uuid.UUID
	title              *string
	description        *string
	content            *map[string]interface{}
	is_public          *bool
	created_at         *time.Time
	updated_at         *time.Time
	last_executed_at   *time.Time
	execution_count    *int
	addexecution_count *int
	clearedFields      map[string]struct{}
	owner              *uuid.UUID
	clearedowner       bool
	shares             map[uuid.UUID]struct{}
	removedshares      map[uuid.UUID]struct{}
	clearedshares      bool
	done               bool
	oldValue           func(context.Context) (*Notebook, error)
	predicates         []predicate.Notebook
}

var _ ent.Mutation = (*NotebookMutation)(nil)

// notebookOption allows management of the mutation configuration using functional options.
type notebookOption func(*NotebookMutation)

// newNotebookMutation creates new mutation for the Notebook entity.
func newNotebookMutation(c config, op Op, opts ...notebookOption) *NotebookMutation {
	m := &NotebookMutation{
		config:        c,
		op:            op,
		typ:           TypeNotebook,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotebookID sets the ID field of the mutation.
func withNotebookID(id uuid.UUID) notebookOption {
	return func(m *NotebookMutation) {
		var (
			err   error
			once  sync.Once
			value *Notebook
		)
		m.oldValue = func(ctx context.Context) (*Notebook, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Notebook.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotebook sets the old Notebook of the mutation.
func withNotebook(node *Notebook) notebookOption {
	return func(m *NotebookMutation) {
		m.oldValue = func(context.Context) (*Notebook, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotebookMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotebookMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Notebook entities.
func (m *NotebookMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotebookMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotebookMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Notebook.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOwnerID sets the "owner_id" field.
func (m *NotebookMutation) SetOwnerID(u uuid.UUID) {
	m.owner = &u
}

// OwnerID returns the value of the "owner_id" field in the mutation.
func (m *NotebookMutation) OwnerID() (r uuid.UUID, exists bool) {
	v := m.owner
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnerID returns the old "owner_id" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldOwnerID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnerID: %w", err)
	}
	return oldValue.OwnerID, nil
}

// ResetOwnerID resets all changes to the "owner_id" field.
func (m *NotebookMutation) ResetOwnerID() {
	m.owner = nil
}

// SetTitle sets the "title" field.
func (m *NotebookMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *NotebookMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *NotebookMutation) ResetTitle() {
	m.title = nil
}

// SetDescription sets the "description" field.
func (m *NotebookMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *NotebookMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldDescription(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *NotebookMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[notebook.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *NotebookMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[notebook.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *NotebookMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, notebook.FieldDescription)
}

// SetContent sets the "content" field.
func (m *NotebookMutation) SetContent(value map[string]interface{}) {
	m.content = &value
}

// Content returns the value of the "content" field in the mutation.
func (m *NotebookMutation) Content() (r map[string]interface{}, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldContent(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *NotebookMutation) ResetContent() {
	m.content = nil
}

// SetIsPublic sets the "is_public" field.
func (m *NotebookMutation) SetIsPublic(b bool) {
	m.is_public = &b
}

// IsPublic returns the value of the "is_public" field in the mutation.
func (m *NotebookMutation) IsPublic() (r bool, exists bool) {
	v := m.is_public
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPublic returns the old "is_public" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldIsPublic(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPublic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPublic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPublic: %w", err)
	}
	return oldValue.IsPublic, nil
}

// ResetIsPublic resets all changes to the "is_public" field.
func (m *NotebookMutation) ResetIsPublic() {
	m.is_public = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *NotebookMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NotebookMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NotebookMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *NotebookMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *NotebookMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *NotebookMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (m *NotebookMutation) SetLastExecutedAt(t time.Time) {
	m.last_executed_at = &t
}

// LastExecutedAt returns the value of the "last_executed_at" field in the mutation.
func (m *NotebookMutation) LastExecutedAt() (r time.Time, exists bool) {
	v := m.last_executed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastExecutedAt returns the old "last_executed_at" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldLastExecutedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastExecutedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastExecutedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastExecutedAt: %w", err)
	}
	return oldValue.LastExecutedAt, nil
}

// ClearLastExecutedAt clears the value of the "last_executed_at" field.
func (m *NotebookMutation) ClearLastExecutedAt() {
	m.last_executed_at = nil
	m.clearedFields[notebook.FieldLastExecutedAt] = struct{}{}
}

// LastExecutedAtCleared returns if the "last_executed_at" field was cleared in this mutation.
func (m *NotebookMutation) LastExecutedAtCleared() bool {
	_, ok := m.clearedFields[notebook.FieldLastExecutedAt]
	return ok
}

// ResetLastExecutedAt resets all changes to the "last_executed_at" field.
func (m *NotebookMutation) ResetLastExecutedAt() {
	m.last_executed_at = nil
	delete(m.clearedFields, notebook.FieldLastExecutedAt)
}

// SetExecutionCount sets the "execution_count" field.
func (m *NotebookMutation) SetExecutionCount(i int) {
	m.execution_count = &i
	m.addexecution_count = nil
}

// ExecutionCount returns the value of the "execution_count" field in the mutation.
func (m *NotebookMutation) ExecutionCount() (r int, exists bool) {
	v := m.execution_count
	if v == nil {
		return
	}
	return *v, true
}

// OldExecutionCount returns the old "execution_count" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldExecutionCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExecutionCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExecutionCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExecutionCount: %w", err)
	}
	return oldValue.ExecutionCount, nil
}

// AddExecutionCount adds i to the "execution_count" field.
func (m *NotebookMutation) AddExecutionCount(i int) {
	if m.addexecution_count != nil {
		*m.addexecution_count += i
	} else {
		m.addexecution_count = &i
	}
}

// AddedExecutionCount returns the value that was added to the "execution_count" field in this mutation.
func (m *NotebookMutation) AddedExecutionCount() (r int, exists bool) {
	v := m.addexecution_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetExecutionCount resets all changes to the "execution_count" field.
func (m *NotebookMutation) ResetExecutionCount() {
	m.execution_count = nil
	m.addexecution_count = nil
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *NotebookMutation) ClearOwner() {
	m.clearedowner = true
	m.clearedFields[notebook.FieldOwnerID] = struct{}{}
}

// OwnerCleared reports if the "owner" edge to the User entity was cleared.
func (m *NotebookMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *NotebookMutation) OwnerIDs() (ids []uuid.UUID) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *NotebookMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// AddShareIDs adds the "shares" edge to the NotebookShare entity by ids.
func (m *NotebookMutation) AddShareIDs(ids ...uuid.UUID) {
	if m.shares == nil {
		m.shares = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.shares[ids[i]] = struct{}{}
	}
}

// ClearShares clears the "shares" edge to the NotebookShare entity.
func (m *NotebookMutation) ClearShares() {
	m.clearedshares = true
}

// SharesCleared reports if the "shares" edge to the NotebookShare entity was cleared.
func (m *NotebookMutation) SharesCleared() bool {
	return m.clearedshares
}

// RemoveShareIDs removes the "shares" edge to the NotebookShare entity by IDs.
func (m *NotebookMutation) RemoveShareIDs(ids ...uuid.UUID) {
	if m.removedshares == nil {
		m.removedshares = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.shares, ids[i])
		m.removedshares[ids[i]] = struct{}{}
	}
}

// RemovedShares returns the removed IDs of the "shares" edge to the NotebookShare entity.
func (m *NotebookMutation) RemovedSharesIDs() (ids []uuid.UUID) {
	for id := range m.removedshares {
		ids = append(ids, id)
	}
	return
}

// SharesIDs returns the "shares" edge IDs in the mutation.
func (m *NotebookMutation) SharesIDs() (ids []uuid.UUID) {
	for id := range m.shares {
		ids = append(ids, id)
	}
	return
}

// ResetShares resets all changes to the "shares" edge.
func (m *NotebookMutation) ResetShares() {
	m.shares = nil
	m.clearedshares = false
	m.removedshares = nil
}

// Where appends a list predicates to the NotebookMutation builder.
func (m *NotebookMutation) Where(ps ...predicate.Notebook) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotebookMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotebookMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Notebook, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotebookMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotebookMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Notebook).
func (m *NotebookMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotebookMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.owner != nil {
		fields = append(fields, notebook.FieldOwnerID)
	}
	if m.title != nil {
		fields = append(fields, notebook.FieldTitle)
	}
	if m.description != nil {
		fields = append(fields, notebook.FieldDescription)
	}
	if m.content != nil {
		fields = append(fields, notebook.FieldContent)
	}
	if m.is_public != nil {
		fields = append(fields, notebook.FieldIsPublic)
	}
	if m.created_at != nil {
		fields = append(fields, notebook.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, notebook.FieldUpdatedAt)
	}
	if m.last_executed_at != nil {
		fields = append(fields, notebook.FieldLastExecutedAt)
	}
	if m.execution_count != nil {
		fields = append(fields, notebook.FieldExecutionCount)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotebookMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notebook.FieldOwnerID:
		return m.OwnerID()
	case notebook.FieldTitle:
		return m.Title()
	case notebook.FieldDescription:
		return m.Description()
	case notebook.FieldContent:
		return m.Content()
	case notebook.FieldIsPublic:
		return m.IsPublic()
	case notebook.FieldCreatedAt:
		return m.CreatedAt()
	case notebook.FieldUpdatedAt:
		return m.UpdatedAt()
	case notebook.FieldLastExecutedAt:
		return m.LastExecutedAt()
	case notebook.FieldExecutionCount:
		return m.ExecutionCount()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotebookMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notebook.FieldOwnerID:
		return m.OldOwnerID(ctx)
	case notebook.FieldTitle:
		return m.OldTitle(ctx)
	case notebook.FieldDescription:
		return m.OldDescription(ctx)
	case notebook.FieldContent:
		return m.OldContent(ctx)
	case notebook.FieldIsPublic:
		return m.OldIsPublic(ctx)
	case notebook.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case notebook.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case notebook.FieldLastExecutedAt:
		return m.OldLastExecutedAt(ctx)
	case notebook.FieldExecutionCount:
		return m.OldExecutionCount(ctx)
	}
	return nil, fmt.Errorf("unknown Notebook field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notebook.FieldOwnerID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnerID(v)
		return nil
	case notebook.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case notebook.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case notebook.FieldContent:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case notebook.FieldIsPublic:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPublic(v)
		return nil
	case notebook.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case notebook.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case notebook.FieldLastExecutedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastExecutedAt(v)
		return nil
	case notebook.FieldExecutionCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExecutionCount(v)
		return nil
	}
	return fmt.Errorf("unknown Notebook field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotebookMutation) AddedFields() []string {
	var fields []string
	if m.addexecution_count != nil {
		fields = append(fields, notebook.FieldExecutionCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotebookMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case notebook.FieldExecutionCount:
		return m.AddedExecutionCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookMutation) AddField(name string, value ent.Value) error {
	switch name {
	case notebook.FieldExecutionCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddExecutionCount(v)
		return nil
	}
	return fmt.Errorf("unknown Notebook numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotebookMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(notebook.FieldDescription) {
		fields = append(fields, notebook.FieldDescription)
	}
	if m.FieldCleared(notebook.FieldLastExecutedAt) {
		fields = append(fields, notebook.FieldLastExecutedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotebookMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotebookMutation) ClearField(name string) error {
	switch name {
	case notebook.FieldDescription:
		m.ClearDescription()
		return nil
	case notebook.FieldLastExecutedAt:
		m.ClearLastExecutedAt()
		return nil
	}
	return fmt.Errorf("unknown Notebook nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotebookMutation) ResetField(name string) error {
	switch name {
	case notebook.FieldOwnerID:
		m.ResetOwnerID()
		return nil
	case notebook.FieldTitle:
		m.ResetTitle()
		return nil
	case notebook.FieldDescription:
		m.ResetDescription()
		return nil
	case notebook.FieldContent:
		m.ResetContent()
		return nil
	case notebook.FieldIsPublic:
		m.ResetIsPublic()
		return nil
	case notebook.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case notebook.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case notebook.FieldLastExecutedAt:
		m.ResetLastExecutedAt()
		return nil
	case notebook.FieldExecutionCount:
		m.ResetExecutionCount()
		return nil
	}
	return fmt.Errorf("unknown Notebook field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotebookMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, notebook.EdgeOwner)
	}
	if m.shares != nil {
		edges = append(edges, notebook.EdgeShares)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotebookMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case notebook.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	case notebook.EdgeShares:
		ids := make([]ent.Value, 0, len(m.shares))
		for id := range m.shares {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotebookMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedshares != nil {
		edges = append(edges, notebook.EdgeShares)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotebookMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case notebook.EdgeShares:
		ids := make([]ent.Value, 0, len(m.removedshares))
		for id := range m.removedshares {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotebookMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, notebook.EdgeOwner)
	}
	if m.clearedshares {
		edges = append(edges, notebook.EdgeShares)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotebookMutation) EdgeCleared(name string) bool {
	switch name {
	case notebook.EdgeOwner:
		return m.clearedowner
	case notebook.EdgeShares:
		return m.clearedshares
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotebookMutation) ClearEdge(name string) error {
	switch name {
	case notebook.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Notebook unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotebookMutation) ResetEdge(name string) error {
	switch name {
	case notebook.EdgeOwner:
		m.ResetOwner()
		return nil
	case notebook.EdgeShares:
		m.ResetShares()
		return nil
	}
	return fmt.Errorf("unknown Notebook edge %s", name)
}

// NotebookShareMutation represents an operation that mutates the NotebookShare nodes in the graph.
type NotebookShareMutation struct {
	config
	op                 Op
	typ                string
	id                 *uuid.UUID
	permission         *notebookshare.Permission
	shared_by_user_id  *uuid.UUID
	created_at         *time.Time
	clearedFields      map[string]struct{}
	notebook           *uuid.UUID
	clearednotebook    bool
	shared_with        *uuid.UUID
	clearedshared_with bool
	done               bool
	oldValue           func(context.Context) (*NotebookShare, error)
	predicates         []predicate.NotebookShare
}

var _ ent.Mutation = (*NotebookShareMutation)(nil)

// notebookshareOption allows management of the mutation configuration using functional options.
type notebookshareOption func(*NotebookShareMutation)

// newNotebookShareMutation creates new mutation for the NotebookShare entity.
func newNotebookShareMutation(c config, op Op, opts ...notebookshareOption) *NotebookShareMutation {
	m := &NotebookShareMutation{
		config:        c,
		op:            op,
		typ:           TypeNotebookShare,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotebookShareID sets the ID field of the mutation.
func withNotebookShareID(id uuid.UUID) notebookshareOption {
	return func(m *NotebookShareMutation) {
		var (
			err   error
			once  sync.Once
			value *NotebookShare
		)
		m.oldValue = func(ctx context.Context) (*NotebookShare, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().NotebookShare.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotebookShare sets the old NotebookShare of the mutation.
func withNotebookShare(node *NotebookShare) notebookshareOption {
	return func(m *NotebookShareMutation) {
		m.oldValue = func(context.Context) (*NotebookShare, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotebookShareMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotebookShareMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of NotebookShare entities.
func (m *NotebookShareMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotebookShareMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotebookShareMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().NotebookShare.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNotebookID sets the "notebook_id" field.
func (m *NotebookShareMutation) SetNotebookID(u uuid.UUID) {
	m.notebook = &u
}

// NotebookID returns the value of the "notebook_id" field in the mutation.
func (m *NotebookShareMutation) NotebookID() (r uuid.UUID, exists bool) {
	v := m.notebook
	if v == nil {
		return
	}
	return *v, true
}

// OldNotebookID returns the old "notebook_id" field's value of the NotebookShare entity.
// If the NotebookShare object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookShareMutation) OldNotebookID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotebookID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotebookID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotebookID: %w", err)
	}
	return oldValue.NotebookID, nil
}

// ResetNotebookID resets all changes to the "notebook_id" field.
func (m *NotebookShareMutation) ResetNotebookID() {
	m.notebook = nil
}

// SetSharedWithUserID sets the "shared_with_user_id" field.
func (m *NotebookShareMutation) SetSharedWithUserID(u uuid.UUID) {
	m.shared_with = &u
}

// SharedWithUserID returns the value of the "shared_with_user_id" field in the mutation.
func (m *NotebookShareMutation) SharedWithUserID() (r uuid.UUID, exists bool) {
	v := m.shared_with
	if v == nil {
		return
	}
	return *v, true
}

// OldSharedWithUserID returns the old "shared_with_user_id" field's value of the NotebookShare entity.
// If the NotebookShare object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookShareMutation) OldSharedWithUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSharedWithUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSharedWithUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSharedWithUserID: %w", err)
	}
	return oldValue.SharedWithUserID, nil
}

// ResetSharedWithUserID resets all changes to the "shared_with_user_id" field.
func (m *NotebookShareMutation) ResetSharedWithUserID() {
	m.shared_with = nil
}

// SetPermission sets the "permission" field.
func (m *NotebookShareMutation) SetPermission(n notebookshare.Permission) {
	m.permission = &n
}

// Permission returns the value of the "permission" field in the mutation.
func (m *NotebookShareMutation) Permission() (r notebookshare.Permission, exists bool) {
	v := m.permission
	if v == nil {
		return
	}
	return *v, true
}

// OldPermission returns the old "permission" field's value of the NotebookShare entity.
// If the NotebookShare object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookShareMutation) OldPermission(ctx context.Context) (v notebookshare.Permission, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPermission is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPermission requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPermission: %w", err)
	}
	return oldValue.Permission, nil
}

// ResetPermission resets all changes to the "permission" field.
func (m *NotebookShareMutation) ResetPermission() {
	m.permission = nil
}

// SetSharedByUserID sets the "shared_by_user_id" field.
func (m *NotebookShareMutation) SetSharedByUserID(u uuid.UUID) {
	m.shared_by_user_id = &u
}

// SharedByUserID returns the value of the "shared_by_user_id" field in the mutation.
func (m *NotebookShareMutation) SharedByUserID() (r uuid.UUID, exists bool) {
	v := m.shared_by_user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSharedByUserID returns the old "shared_by_user_id" field's value of the NotebookShare entity.
// If the NotebookShare object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookShareMutation) OldSharedByUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSharedByUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSharedByUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSharedByUserID: %w", err)
	}
	return oldValue.SharedByUserID, nil
}

// ResetSharedByUserID resets all changes to the "shared_by_user_id" field.
func (m *NotebookShareMutation) ResetSharedByUserID() {
	m.shared_by_user_id = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *NotebookShareMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NotebookShareMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the NotebookShare entity.
// If the NotebookShare object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookShareMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NotebookShareMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearNotebook clears the "notebook" edge to the Notebook entity.
func (m *NotebookShareMutation) ClearNotebook() {
	m.clearednotebook = true
	m.clearedFields[notebookshare.FieldNotebookID] = struct{}{}
}

// NotebookCleared reports if the "notebook" edge to the Notebook entity was cleared.
func (m *NotebookShareMutation) NotebookCleared() bool {
	return m.clearednotebook
}

// NotebookIDs returns the "notebook" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// NotebookID instead. It exists only for internal usage by the builders.
func (m *NotebookShareMutation) NotebookIDs() (ids []uuid.UUID) {
	if id := m.notebook; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetNotebook resets all changes to the "notebook" edge.
func (m *NotebookShareMutation) ResetNotebook() {
	m.notebook = nil
	m.clearednotebook = false
}

// SetSharedWithID sets the "shared_with" edge to the User entity by id.
func (m *NotebookShareMutation) SetSharedWithID(id uuid.UUID) {
	m.shared_with = &id
}

// ClearSharedWith clears the "shared_with" edge to the User entity.
func (m *NotebookShareMutation) ClearSharedWith() {
	m.clearedshared_with = true
	m.clearedFields[notebookshare.FieldSharedWithUserID] = struct{}{}
}

// SharedWithCleared reports if the "shared_with" edge to the User entity was cleared.
func (m *NotebookShareMutation) SharedWithCleared() bool {
	return m.clearedshared_with
}

// SharedWithID returns the "shared_with" edge ID in the mutation.
func (m *NotebookShareMutation) SharedWithID() (id uuid.UUID, exists bool) {
	if m.shared_with != nil {
		return *m.shared_with, true
	}
	return
}

// SharedWithIDs returns the "shared_with" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SharedWithID instead. It exists only for internal usage by the builders.
func (m *NotebookShareMutation) SharedWithIDs() (ids []uuid.UUID) {
	if id := m.shared_with; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSharedWith resets all changes to the "shared_with" edge.
func (m *NotebookShareMutation) ResetSharedWith() {
	m.shared_with = nil
	m.clearedshared_with = false
}

// Where appends a list predicates to the NotebookShareMutation builder.
func (m *NotebookShareMutation) Where(ps ...predicate.NotebookShare) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotebookShareMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotebookShareMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.NotebookShare, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotebookShareMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotebookShareMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (NotebookShare).
func (m *NotebookShareMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotebookShareMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.notebook != nil {
		fields = append(fields, notebookshare.FieldNotebookID)
	}
	if m.shared_with != nil {
		fields = append(fields, notebookshare.FieldSharedWithUserID)
	}
	if m.permission != nil {
		fields = append(fields, notebookshare.FieldPermission)
	}
	if m.shared_by_user_id != nil {
		fields = append(fields, notebookshare.FieldSharedByUserID)
	}
	if m.created_at != nil {
		fields = append(fields, notebookshare.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotebookShareMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notebookshare.FieldNotebookID:
		return m.NotebookID()
	case notebookshare.FieldSharedWithUserID:
		return m.SharedWithUserID()
	case notebookshare.FieldPermission:
		return m.Permission()
	case notebookshare.FieldSharedByUserID:
		return m.SharedByUserID()
	case notebookshare.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotebookShareMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notebookshare.FieldNotebookID:
		return m.OldNotebookID(ctx)
	case notebookshare.FieldSharedWithUserID:
		return m.OldSharedWithUserID(ctx)
	case notebookshare.FieldPermission:
		return m.OldPermission(ctx)
	case notebookshare.FieldSharedByUserID:
		return m.OldSharedByUserID(ctx)
	case notebookshare.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown NotebookShare field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookShareMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notebookshare.FieldNotebookID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotebookID(v)
		return nil
	case notebookshare.FieldSharedWithUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSharedWithUserID(v)
		return nil
	case notebookshare.FieldPermission:
		v, ok := value.(notebookshare.Permission)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPermission(v)
		return nil
	case notebookshare.FieldSharedByUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSharedByUserID(v)
		return nil
	case notebookshare.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown NotebookShare field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotebookShareMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotebookShareMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookShareMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown NotebookShare numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotebookShareMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotebookShareMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotebookShareMutation) ClearField(name string) error {
	return fmt.Errorf("unknown NotebookShare nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotebookShareMutation) ResetField(name string) error {
	switch name {
	case notebookshare.FieldNotebookID:
		m.ResetNotebookID()
		return nil
	case notebookshare.FieldSharedWithUserID:
		m.ResetSharedWithUserID()
		return nil
	case notebookshare.FieldPermission:
		m.ResetPermission()
		return nil
	case notebookshare.FieldSharedByUserID:
		m.ResetSharedByUserID()
		return nil
	case notebookshare.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown NotebookShare field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotebookShareMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.notebook != nil {
		edges = append(edges, notebookshare.EdgeNotebook)
	}
	if m.shared_with != nil {
		edges = append(edges, notebookshare.EdgeSharedWith)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotebookShareMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case notebookshare.EdgeNotebook:
		if id := m.notebook; id != nil {
			return []ent.Value{*id}
		}
	case notebookshare.EdgeSharedWith:
		if id := m.shared_with; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotebookShareMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotebookShareMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotebookShareMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearednotebook {
		edges = append(edges, notebookshare.EdgeNotebook)
	}
	if m.clearedshared_with {
		edges = append(edges, notebookshare.EdgeSharedWith)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotebookShareMutation) EdgeCleared(name string) bool {
	switch name {
	case notebookshare.EdgeNotebook:
		return m.clearednotebook
	case notebookshare.EdgeSharedWith:
		return m.clearedshared_with
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotebookShareMutation) ClearEdge(name string) error {
	switch name {
	case notebookshare.EdgeNotebook:
		m.ClearNotebook()
		return nil
	case notebookshare.EdgeSharedWith:
		m.ClearSharedWith()
		return nil
	}
	return fmt.Errorf("unknown NotebookShare unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotebookShareMutation) ResetEdge(name string) error {
	switch name {
	case notebookshare.EdgeNotebook:
		m.ResetNotebook()
		return nil
	case notebookshare.EdgeSharedWith:
		m.ResetSharedWith()
		return nil
	}
	return fmt.Errorf("unknown NotebookShare edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                      Op
	typ                     string
	id                      *uuid.UUID
	email                   *string
	password_hash           *string
	name                    *string
	avatar_url              *string
	created_at              *time.Time
	updated_at              *time.Time
	last_login_at           *time.Time
	is_active               *bool
	clearedFields           map[string]struct{}
	notebooks               map[uuid.UUID]struct{}
	removednotebooks        map[uuid.UUID]struct{}
	clearednotebooks        bool
	shared_notebooks        map[uuid.UUID]struct{}
	removedshared_notebooks map[uuid.UUID]struct{}
	clearedshared_notebooks bool
	done                    bool
	oldValue                func(context.Context) (*User, error)
	predicates              []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id uuid.UUID) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetPasswordHash sets the "password_hash" field.
func (m *UserMutation) SetPasswordHash(s string) {
	m.password_hash = &s
}

// PasswordHash returns the value of the "password_hash" field in the mutation.
func (m *UserMutation) PasswordHash() (r string, exists bool) {
	v := m.password_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldPasswordHash returns the old "password_hash" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPasswordHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPasswordHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPasswordHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPasswordHash: %w", err)
	}
	return oldValue.PasswordHash, nil
}

// ResetPasswordHash resets all changes to the "password_hash" field.
func (m *UserMutation) ResetPasswordHash() {
	m.password_hash = nil
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetAvatarURL sets the "avatar_url" field.
func (m *UserMutation) SetAvatarURL(s string) {
	m.avatar_url = &s
}

// AvatarURL returns the value of the "avatar_url" field in the mutation.
func (m *UserMutation) AvatarURL() (r string, exists bool) {
	v := m.avatar_url
	if v == nil {
		return
	}
	return *v, true
}

// OldAvatarURL returns the old "avatar_url" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldAvatarURL(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAvatarURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAvatarURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAvatarURL: %w", err)
	}
	return oldValue.AvatarURL, nil
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (m *UserMutation) ClearAvatarURL() {
	m.avatar_url = nil
	m.clearedFields[user.FieldAvatarURL] = struct{}{}
}

// AvatarURLCleared returns if the "avatar_url" field was cleared in this mutation.
func (m *UserMutation) AvatarURLCleared() bool {
	_, ok := m.clearedFields[user.FieldAvatarURL]
	return ok
}

// ResetAvatarURL resets all changes to the "avatar_url" field.
func (m *UserMutation) ResetAvatarURL() {
	m.avatar_url = nil
	delete(m.clearedFields, user.FieldAvatarURL)
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetLastLoginAt sets the "last_login_at" field.
func (m *UserMutation) SetLastLoginAt(t time.Time) {
	m.last_login_at = &t
}

// LastLoginAt returns the value of the "last_login_at" field in the mutation.
func (m *UserMutation) LastLoginAt() (r time.Time, exists bool) {
	v := m.last_login_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastLoginAt returns the old "last_login_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLastLoginAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastLoginAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastLoginAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastLoginAt: %w", err)
	}
	return oldValue.LastLoginAt, nil
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (m *UserMutation) ClearLastLoginAt() {
	m.last_login_at = nil
	m.clearedFields[user.FieldLastLoginAt] = struct{}{}
}

// LastLoginAtCleared returns if the "last_login_at" field was cleared in this mutation.
func (m *UserMutation) LastLoginAtCleared() bool {
	_, ok := m.clearedFields[user.FieldLastLoginAt]
	return ok
}

// ResetLastLoginAt resets all changes to the "last_login_at" field.
func (m *UserMutation) ResetLastLoginAt() {
	m.last_login_at = nil
	delete(m.clearedFields, user.FieldLastLoginAt)
}

// SetIsActive sets the "is_active" field.
func (m *UserMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *UserMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *UserMutation) ResetIsActive() {
	m.is_active = nil
}

// AddNotebookIDs adds the "notebooks" edge to the Notebook entity by ids.
func (m *UserMutation) AddNotebookIDs(ids ...uuid.UUID) {
	if m.notebooks == nil {
		m.notebooks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.notebooks[ids[i]] = struct{}{}
	}
}

// ClearNotebooks clears the "notebooks" edge to the Notebook entity.
func (m *UserMutation) ClearNotebooks() {
	m.clearednotebooks = true
}

// NotebooksCleared reports if the "notebooks" edge to the Notebook entity was cleared.
func (m *UserMutation) NotebooksCleared() bool {
	return m.clearednotebooks
}

// RemoveNotebookIDs removes the "notebooks" edge to the Notebook entity by IDs.
func (m *UserMutation) RemoveNotebookIDs(ids ...uuid.UUID) {
	if m.removednotebooks == nil {
		m.removednotebooks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.notebooks, ids[i])
		m.removednotebooks[ids[i]] = struct{}{}
	}
}

// RemovedNotebooks returns the removed IDs of the "notebooks" edge to the Notebook entity.
func (m *UserMutation) RemovedNotebooksIDs() (ids []uuid.UUID) {
	for id := range m.removednotebooks {
		ids = append(ids, id)
	}
	return
}

// NotebooksIDs returns the "notebooks" edge IDs in the mutation.
func (m *UserMutation) NotebooksIDs() (ids []uuid.UUID) {
	for id := range m.notebooks {
		ids = append(ids, id)
	}
	return
}

// ResetNotebooks resets all changes to the "notebooks" edge.
func (m *UserMutation) ResetNotebooks() {
	m.notebooks = nil
	m.clearednotebooks = false
	m.removednotebooks = nil
}

// AddSharedNotebookIDs adds the "shared_notebooks" edge to the NotebookShare entity by ids.
func (m *UserMutation) AddSharedNotebookIDs(ids ...uuid.UUID) {
	if m.shared_notebooks == nil {
		m.shared_notebooks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.shared_notebooks[ids[i]] = struct{}{}
	}
}

// ClearSharedNotebooks clears the "shared_notebooks" edge to the NotebookShare entity.
func (m *UserMutation) ClearSharedNotebooks() {
	m.clearedshared_notebooks = true
}

// SharedNotebooksCleared reports if the "shared_notebooks" edge to the NotebookShare entity was cleared.
func (m *UserMutation) SharedNotebooksCleared() bool {
	return m.clearedshared_notebooks
}

// RemoveSharedNotebookIDs removes the "shared_notebooks" edge to the NotebookShare entity by IDs.
func (m *UserMutation) RemoveSharedNotebookIDs(ids ...uuid.UUID) {
	if m.removedshared_notebooks == nil {
		m.removedshared_notebooks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.shared_notebooks, ids[i])
		m.removedshared_notebooks[ids[i]] = struct{}{}
	}
}

// RemovedSharedNotebooks returns the removed IDs of the "shared_notebooks" edge to the NotebookShare entity.
func (m *UserMutation) RemovedSharedNotebooksIDs() (ids []uuid.UUID) {
	for id := range m.removedshared_notebooks {
		ids = append(ids, id)
	}
	return
}

// SharedNotebooksIDs returns the "shared_notebooks" edge IDs in the mutation.
func (m *UserMutation) SharedNotebooksIDs() (ids []uuid.UUID) {
	for id := range m.shared_notebooks {
		ids = append(ids, id)
	}
	return
}

// ResetSharedNotebooks resets all changes to the "shared_notebooks" edge.
func (m *UserMutation) ResetSharedNotebooks() {
	m.shared_notebooks = nil
	m.clearedshared_notebooks = false
	m.removedshared_notebooks = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.password_hash != nil {
		fields = append(fields, user.FieldPasswordHash)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.avatar_url != nil {
		fields = append(fields, user.FieldAvatarURL)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	if m.last_login_at != nil {
		fields = append(fields, user.FieldLastLoginAt)
	}
	if m.is_active != nil {
		fields = append(fields, user.FieldIsActive)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldEmail:
		return m.Email()
	case user.FieldPasswordHash:
		return m.PasswordHash()
	case user.FieldName:
		return m.Name()
	case user.FieldAvatarURL:
		return m.AvatarURL()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	case user.FieldLastLoginAt:
		return m.LastLoginAt()
	case user.FieldIsActive:
		return m.IsActive()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldPasswordHash:
		return m.OldPasswordHash(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldAvatarURL:
		return m.OldAvatarURL(ctx)
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case user.FieldLastLoginAt:
		return m.OldLastLoginAt(ctx)
	case user.FieldIsActive:
		return m.OldIsActive(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldPasswordHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPasswordHash(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldAvatarURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvatarURL(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case user.FieldLastLoginAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastLoginAt(v)
		return nil
	case user.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldAvatarURL) {
		fields = append(fields, user.FieldAvatarURL)
	}
	if m.FieldCleared(user.FieldLastLoginAt) {
		fields = append(fields, user.FieldLastLoginAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldAvatarURL:
		m.ClearAvatarURL()
		return nil
	case user.FieldLastLoginAt:
		m.ClearLastLoginAt()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldPasswordHash:
		m.ResetPasswordHash()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldAvatarURL:
		m.ResetAvatarURL()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case user.FieldLastLoginAt:
		m.ResetLastLoginAt()
		return nil
	case user.FieldIsActive:
		m.ResetIsActive()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.notebooks != nil {
		edges = append(edges, user.EdgeNotebooks)
	}
	if m.shared_notebooks != nil {
		edges = append(edges, user.EdgeSharedNotebooks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeNotebooks:
		ids := make([]ent.Value, 0, len(m.notebooks))
		for id := range m.notebooks {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeSharedNotebooks:
		ids := make([]ent.Value, 0, len(m.shared_notebooks))
		for id := range m.shared_notebooks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removednotebooks != nil {
		edges = append(edges, user.EdgeNotebooks)
	}
	if m.removedshared_notebooks != nil {
		edges = append(edges, user.EdgeSharedNotebooks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeNotebooks:
		ids := make([]ent.Value, 0, len(m.removednotebooks))
		for id := range m.removednotebooks {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeSharedNotebooks:
		ids := make([]ent.Value, 0, len(m.removedshared_notebooks))
		for id := range m.removedshared_notebooks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearednotebooks {
		edges = append(edges, user.EdgeNotebooks)
	}
	if m.clearedshared_notebooks {
		edges = append(edges, user.EdgeSharedNotebooks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeNotebooks:
		return m.clearednotebooks
	case user.EdgeSharedNotebooks:
		return m.clearedshared_notebooks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeNotebooks:
		m.ResetNotebooks()
		return nil
	case user.EdgeSharedNotebooks:
		m.ResetSharedNotebooks()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
