// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"
	"gladiator/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookUpdate is the builder for updating Notebook entities.
type NotebookUpdate struct {
	config
	hooks    []Hook
	mutation *NotebookMutation
}

// Where appends a list predicates to the NotebookUpdate builder.
func (nu *NotebookUpdate) Where(ps ...predicate.Notebook) *NotebookUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetOwnerID sets the "owner_id" field.
func (nu *NotebookUpdate) SetOwnerID(u uuid.UUID) *NotebookUpdate {
	nu.mutation.SetOwnerID(u)
	return nu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableOwnerID(u *uuid.UUID) *NotebookUpdate {
	if u != nil {
		nu.SetOwnerID(*u)
	}
	return nu
}

// SetTitle sets the "title" field.
func (nu *NotebookUpdate) SetTitle(s string) *NotebookUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableTitle(s *string) *NotebookUpdate {
	if s != nil {
		nu.SetTitle(*s)
	}
	return nu
}

// SetDescription sets the "description" field.
func (nu *NotebookUpdate) SetDescription(s string) *NotebookUpdate {
	nu.mutation.SetDescription(s)
	return nu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableDescription(s *string) *NotebookUpdate {
	if s != nil {
		nu.SetDescription(*s)
	}
	return nu
}

// ClearDescription clears the value of the "description" field.
func (nu *NotebookUpdate) ClearDescription() *NotebookUpdate {
	nu.mutation.ClearDescription()
	return nu
}

// SetContent sets the "content" field.
func (nu *NotebookUpdate) SetContent(m map[string]interface{}) *NotebookUpdate {
	nu.mutation.SetContent(m)
	return nu
}

// SetIsPublic sets the "is_public" field.
func (nu *NotebookUpdate) SetIsPublic(b bool) *NotebookUpdate {
	nu.mutation.SetIsPublic(b)
	return nu
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableIsPublic(b *bool) *NotebookUpdate {
	if b != nil {
		nu.SetIsPublic(*b)
	}
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NotebookUpdate) SetUpdatedAt(t time.Time) *NotebookUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (nu *NotebookUpdate) SetLastExecutedAt(t time.Time) *NotebookUpdate {
	nu.mutation.SetLastExecutedAt(t)
	return nu
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableLastExecutedAt(t *time.Time) *NotebookUpdate {
	if t != nil {
		nu.SetLastExecutedAt(*t)
	}
	return nu
}

// ClearLastExecutedAt clears the value of the "last_executed_at" field.
func (nu *NotebookUpdate) ClearLastExecutedAt() *NotebookUpdate {
	nu.mutation.ClearLastExecutedAt()
	return nu
}

// SetExecutionCount sets the "execution_count" field.
func (nu *NotebookUpdate) SetExecutionCount(i int) *NotebookUpdate {
	nu.mutation.ResetExecutionCount()
	nu.mutation.SetExecutionCount(i)
	return nu
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (nu *NotebookUpdate) SetNillableExecutionCount(i *int) *NotebookUpdate {
	if i != nil {
		nu.SetExecutionCount(*i)
	}
	return nu
}

// AddExecutionCount adds i to the "execution_count" field.
func (nu *NotebookUpdate) AddExecutionCount(i int) *NotebookUpdate {
	nu.mutation.AddExecutionCount(i)
	return nu
}

// SetOwner sets the "owner" edge to the User entity.
func (nu *NotebookUpdate) SetOwner(u *User) *NotebookUpdate {
	return nu.SetOwnerID(u.ID)
}

// AddShareIDs adds the "shares" edge to the NotebookShare entity by IDs.
func (nu *NotebookUpdate) AddShareIDs(ids ...uuid.UUID) *NotebookUpdate {
	nu.mutation.AddShareIDs(ids...)
	return nu
}

// AddShares adds the "shares" edges to the NotebookShare entity.
func (nu *NotebookUpdate) AddShares(n ...*NotebookShare) *NotebookUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.AddShareIDs(ids...)
}

// Mutation returns the NotebookMutation object of the builder.
func (nu *NotebookUpdate) Mutation() *NotebookMutation {
	return nu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (nu *NotebookUpdate) ClearOwner() *NotebookUpdate {
	nu.mutation.ClearOwner()
	return nu
}

// ClearShares clears all "shares" edges to the NotebookShare entity.
func (nu *NotebookUpdate) ClearShares() *NotebookUpdate {
	nu.mutation.ClearShares()
	return nu
}

// RemoveShareIDs removes the "shares" edge to NotebookShare entities by IDs.
func (nu *NotebookUpdate) RemoveShareIDs(ids ...uuid.UUID) *NotebookUpdate {
	nu.mutation.RemoveShareIDs(ids...)
	return nu
}

// RemoveShares removes "shares" edges to NotebookShare entities.
func (nu *NotebookUpdate) RemoveShares(n ...*NotebookShare) *NotebookUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.RemoveShareIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotebookUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotebookUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotebookUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotebookUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NotebookUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := notebook.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotebookUpdate) check() error {
	if v, ok := nu.mutation.Title(); ok {
		if err := notebook.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notebook.title": %w`, err)}
		}
	}
	if v, ok := nu.mutation.ExecutionCount(); ok {
		if err := notebook.ExecutionCountValidator(v); err != nil {
			return &ValidationError{Name: "execution_count", err: fmt.Errorf(`ent: validator failed for field "Notebook.execution_count": %w`, err)}
		}
	}
	if nu.mutation.OwnerCleared() && len(nu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notebook.owner"`)
	}
	return nil
}

func (nu *NotebookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notebook.Table, notebook.Columns, sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.SetField(notebook.FieldTitle, field.TypeString, value)
	}
	if value, ok := nu.mutation.Description(); ok {
		_spec.SetField(notebook.FieldDescription, field.TypeString, value)
	}
	if nu.mutation.DescriptionCleared() {
		_spec.ClearField(notebook.FieldDescription, field.TypeString)
	}
	if value, ok := nu.mutation.Content(); ok {
		_spec.SetField(notebook.FieldContent, field.TypeJSON, value)
	}
	if value, ok := nu.mutation.IsPublic(); ok {
		_spec.SetField(notebook.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(notebook.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := nu.mutation.LastExecutedAt(); ok {
		_spec.SetField(notebook.FieldLastExecutedAt, field.TypeTime, value)
	}
	if nu.mutation.LastExecutedAtCleared() {
		_spec.ClearField(notebook.FieldLastExecutedAt, field.TypeTime)
	}
	if value, ok := nu.mutation.ExecutionCount(); ok {
		_spec.SetField(notebook.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := nu.mutation.AddedExecutionCount(); ok {
		_spec.AddField(notebook.FieldExecutionCount, field.TypeInt, value)
	}
	if nu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebook.OwnerTable,
			Columns: []string{notebook.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebook.OwnerTable,
			Columns: []string{notebook.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedSharesIDs(); len(nodes) > 0 && !nu.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notebook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NotebookUpdateOne is the builder for updating a single Notebook entity.
type NotebookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotebookMutation
}

// SetOwnerID sets the "owner_id" field.
func (nuo *NotebookUpdateOne) SetOwnerID(u uuid.UUID) *NotebookUpdateOne {
	nuo.mutation.SetOwnerID(u)
	return nuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableOwnerID(u *uuid.UUID) *NotebookUpdateOne {
	if u != nil {
		nuo.SetOwnerID(*u)
	}
	return nuo
}

// SetTitle sets the "title" field.
func (nuo *NotebookUpdateOne) SetTitle(s string) *NotebookUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableTitle(s *string) *NotebookUpdateOne {
	if s != nil {
		nuo.SetTitle(*s)
	}
	return nuo
}

// SetDescription sets the "description" field.
func (nuo *NotebookUpdateOne) SetDescription(s string) *NotebookUpdateOne {
	nuo.mutation.SetDescription(s)
	return nuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableDescription(s *string) *NotebookUpdateOne {
	if s != nil {
		nuo.SetDescription(*s)
	}
	return nuo
}

// ClearDescription clears the value of the "description" field.
func (nuo *NotebookUpdateOne) ClearDescription() *NotebookUpdateOne {
	nuo.mutation.ClearDescription()
	return nuo
}

// SetContent sets the "content" field.
func (nuo *NotebookUpdateOne) SetContent(m map[string]interface{}) *NotebookUpdateOne {
	nuo.mutation.SetContent(m)
	return nuo
}

// SetIsPublic sets the "is_public" field.
func (nuo *NotebookUpdateOne) SetIsPublic(b bool) *NotebookUpdateOne {
	nuo.mutation.SetIsPublic(b)
	return nuo
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableIsPublic(b *bool) *NotebookUpdateOne {
	if b != nil {
		nuo.SetIsPublic(*b)
	}
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NotebookUpdateOne) SetUpdatedAt(t time.Time) *NotebookUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (nuo *NotebookUpdateOne) SetLastExecutedAt(t time.Time) *NotebookUpdateOne {
	nuo.mutation.SetLastExecutedAt(t)
	return nuo
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableLastExecutedAt(t *time.Time) *NotebookUpdateOne {
	if t != nil {
		nuo.SetLastExecutedAt(*t)
	}
	return nuo
}

// ClearLastExecutedAt clears the value of the "last_executed_at" field.
func (nuo *NotebookUpdateOne) ClearLastExecutedAt() *NotebookUpdateOne {
	nuo.mutation.ClearLastExecutedAt()
	return nuo
}

// SetExecutionCount sets the "execution_count" field.
func (nuo *NotebookUpdateOne) SetExecutionCount(i int) *NotebookUpdateOne {
	nuo.mutation.ResetExecutionCount()
	nuo.mutation.SetExecutionCount(i)
	return nuo
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (nuo *NotebookUpdateOne) SetNillableExecutionCount(i *int) *NotebookUpdateOne {
	if i != nil {
		nuo.SetExecutionCount(*i)
	}
	return nuo
}

// AddExecutionCount adds i to the "execution_count" field.
func (nuo *NotebookUpdateOne) AddExecutionCount(i int) *NotebookUpdateOne {
	nuo.mutation.AddExecutionCount(i)
	return nuo
}

// SetOwner sets the "owner" edge to the User entity.
func (nuo *NotebookUpdateOne) SetOwner(u *User) *NotebookUpdateOne {
	return nuo.SetOwnerID(u.ID)
}

// AddShareIDs adds the "shares" edge to the NotebookShare entity by IDs.
func (nuo *NotebookUpdateOne) AddShareIDs(ids ...uuid.UUID) *NotebookUpdateOne {
	nuo.mutation.AddShareIDs(ids...)
	return nuo
}

// AddShares adds the "shares" edges to the NotebookShare entity.
func (nuo *NotebookUpdateOne) AddShares(n ...*NotebookShare) *NotebookUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.AddShareIDs(ids...)
}

// Mutation returns the NotebookMutation object of the builder.
func (nuo *NotebookUpdateOne) Mutation() *NotebookMutation {
	return nuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (nuo *NotebookUpdateOne) ClearOwner() *NotebookUpdateOne {
	nuo.mutation.ClearOwner()
	return nuo
}

// ClearShares clears all "shares" edges to the NotebookShare entity.
func (nuo *NotebookUpdateOne) ClearShares() *NotebookUpdateOne {
	nuo.mutation.ClearShares()
	return nuo
}

// RemoveShareIDs removes the "shares" edge to NotebookShare entities by IDs.
func (nuo *NotebookUpdateOne) RemoveShareIDs(ids ...uuid.UUID) *NotebookUpdateOne {
	nuo.mutation.RemoveShareIDs(ids...)
	return nuo
}

// RemoveShares removes "shares" edges to NotebookShare entities.
func (nuo *NotebookUpdateOne) RemoveShares(n ...*NotebookShare) *NotebookUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.RemoveShareIDs(ids...)
}

// Where appends a list predicates to the NotebookUpdate builder.
func (nuo *NotebookUpdateOne) Where(ps ...predicate.Notebook) *NotebookUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotebookUpdateOne) Select(field string, fields ...string) *NotebookUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notebook entity.
func (nuo *NotebookUpdateOne) Save(ctx context.Context) (*Notebook, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotebookUpdateOne) SaveX(ctx context.Context) *Notebook {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotebookUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotebookUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NotebookUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := notebook.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotebookUpdateOne) check() error {
	if v, ok := nuo.mutation.Title(); ok {
		if err := notebook.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notebook.title": %w`, err)}
		}
	}
	if v, ok := nuo.mutation.ExecutionCount(); ok {
		if err := notebook.ExecutionCountValidator(v); err != nil {
			return &ValidationError{Name: "execution_count", err: fmt.Errorf(`ent: validator failed for field "Notebook.execution_count": %w`, err)}
		}
	}
	if nuo.mutation.OwnerCleared() && len(nuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notebook.owner"`)
	}
	return nil
}

func (nuo *NotebookUpdateOne) sqlSave(ctx context.Context) (_node *Notebook, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notebook.Table, notebook.Columns, sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notebook.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notebook.FieldID)
		for _, f := range fields {
			if !notebook.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notebook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.SetField(notebook.FieldTitle, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Description(); ok {
		_spec.SetField(notebook.FieldDescription, field.TypeString, value)
	}
	if nuo.mutation.DescriptionCleared() {
		_spec.ClearField(notebook.FieldDescription, field.TypeString)
	}
	if value, ok := nuo.mutation.Content(); ok {
		_spec.SetField(notebook.FieldContent, field.TypeJSON, value)
	}
	if value, ok := nuo.mutation.IsPublic(); ok {
		_spec.SetField(notebook.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notebook.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := nuo.mutation.LastExecutedAt(); ok {
		_spec.SetField(notebook.FieldLastExecutedAt, field.TypeTime, value)
	}
	if nuo.mutation.LastExecutedAtCleared() {
		_spec.ClearField(notebook.FieldLastExecutedAt, field.TypeTime)
	}
	if value, ok := nuo.mutation.ExecutionCount(); ok {
		_spec.SetField(notebook.FieldExecutionCount, field.TypeInt, value)
	}
	if value, ok := nuo.mutation.AddedExecutionCount(); ok {
		_spec.AddField(notebook.FieldExecutionCount, field.TypeInt, value)
	}
	if nuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebook.OwnerTable,
			Columns: []string{notebook.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebook.OwnerTable,
			Columns: []string{notebook.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedSharesIDs(); len(nodes) > 0 && !nuo.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notebook{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notebook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
