// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NotebookShare is the model entity for the NotebookShare schema.
type NotebookShare struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// NotebookID holds the value of the "notebook_id" field.
	NotebookID uuid.UUID `json:"notebook_id,omitempty"`
	// SharedWithUserID holds the value of the "shared_with_user_id" field.
	SharedWithUserID uuid.UUID `json:"shared_with_user_id,omitempty"`
	// Permission holds the value of the "permission" field.
	Permission notebookshare.Permission `json:"permission,omitempty"`
	// SharedByUserID holds the value of the "shared_by_user_id" field.
	SharedByUserID uuid.UUID `json:"shared_by_user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotebookShareQuery when eager-loading is set.
	Edges        NotebookShareEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotebookShareEdges holds the relations/edges for other nodes in the graph.
type NotebookShareEdges struct {
	// Notebook holds the value of the notebook edge.
	Notebook *Notebook `json:"notebook,omitempty"`
	// SharedWith holds the value of the shared_with edge.
	SharedWith *User `json:"shared_with,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NotebookOrErr returns the Notebook value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotebookShareEdges) NotebookOrErr() (*Notebook, error) {
	if e.Notebook != nil {
		return e.Notebook, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: notebook.Label}
	}
	return nil, &NotLoadedError{edge: "notebook"}
}

// SharedWithOrErr returns the SharedWith value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotebookShareEdges) SharedWithOrErr() (*User, error) {
	if e.SharedWith != nil {
		return e.SharedWith, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "shared_with"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotebookShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notebookshare.FieldPermission:
			values[i] = new(sql.NullString)
		case notebookshare.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case notebookshare.FieldID, notebookshare.FieldNotebookID, notebookshare.FieldSharedWithUserID, notebookshare.FieldSharedByUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotebookShare fields.
func (ns *NotebookShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notebookshare.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ns.ID = *value
			}
		case notebookshare.FieldNotebookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field notebook_id", values[i])
			} else if value != nil {
				ns.NotebookID = *value
			}
		case notebookshare.FieldSharedWithUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shared_with_user_id", values[i])
			} else if value != nil {
				ns.SharedWithUserID = *value
			}
		case notebookshare.FieldPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission", values[i])
			} else if value.Valid {
				ns.Permission = notebookshare.Permission(value.String)
			}
		case notebookshare.FieldSharedByUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shared_by_user_id", values[i])
			} else if value != nil {
				ns.SharedByUserID = *value
			}
		case notebookshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ns.CreatedAt = value.Time
			}
		default:
			ns.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotebookShare.
// This includes values selected through modifiers, order, etc.
func (ns *NotebookShare) Value(name string) (ent.Value, error) {
	return ns.selectValues.Get(name)
}

// QueryNotebook queries the "notebook" edge of the NotebookShare entity.
func (ns *NotebookShare) QueryNotebook() *NotebookQuery {
	return NewNotebookShareClient(ns.config).QueryNotebook(ns)
}

// QuerySharedWith queries the "shared_with" edge of the NotebookShare entity.
func (ns *NotebookShare) QuerySharedWith() *UserQuery {
	return NewNotebookShareClient(ns.config).QuerySharedWith(ns)
}

// Update returns a builder for updating this NotebookShare.
// Note that you need to call NotebookShare.Unwrap() before calling this method if this NotebookShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (ns *NotebookShare) Update() *NotebookShareUpdateOne {
	return NewNotebookShareClient(ns.config).UpdateOne(ns)
}

// Unwrap unwraps the NotebookShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ns *NotebookShare) Unwrap() *NotebookShare {
	_tx, ok := ns.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotebookShare is not a transactional entity")
	}
	ns.config.driver = _tx.drv
	return ns
}

// String implements the fmt.Stringer.
func (ns *NotebookShare) String() string {
	var builder strings.Builder
	builder.WriteString("NotebookShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ns.ID))
	builder.WriteString("notebook_id=")
	builder.WriteString(fmt.Sprintf("%v", ns.NotebookID))
	builder.WriteString(", ")
	builder.WriteString("shared_with_user_id=")
	builder.WriteString(fmt.Sprintf("%v", ns.SharedWithUserID))
	builder.WriteString(", ")
	builder.WriteString("permission=")
	builder.WriteString(fmt.Sprintf("%v", ns.Permission))
	builder.WriteString(", ")
	builder.WriteString("shared_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", ns.SharedByUserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ns.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotebookShares is a parsable slice of NotebookShare.
type NotebookShares []*NotebookShare
