// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gladiator/ent/notebook"
	"gladiator/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotebookDelete is the builder for deleting a Notebook entity.
type NotebookDelete struct {
	config
	hooks    []Hook
	mutation *NotebookMutation
}

// Where appends a list predicates to the NotebookDelete builder.
func (nd *NotebookDelete) Where(ps ...predicate.Notebook) *NotebookDelete {
	nd.mutation.Where(ps...)
	return nd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nd *NotebookDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nd.sqlExec, nd.mutation, nd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nd *NotebookDelete) ExecX(ctx context.Context) int {
	n, err := nd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nd *NotebookDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notebook.Table, sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID))
	if ps := nd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nd.mutation.done = true
	return affected, err
}

// NotebookDeleteOne is the builder for deleting a single Notebook entity.
type NotebookDeleteOne struct {
	nd *NotebookDelete
}

// Where appends a list predicates to the NotebookDelete builder.
func (ndo *NotebookDeleteOne) Where(ps ...predicate.Notebook) *NotebookDeleteOne {
	ndo.nd.mutation.Where(ps...)
	return ndo
}

// Exec executes the deletion query.
func (ndo *NotebookDeleteOne) Exec(ctx context.Context) error {
	n, err := ndo.nd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notebook.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ndo *NotebookDeleteOne) ExecX(ctx context.Context) {
	if err := ndo.Exec(ctx); err != nil {
		panic(err)
	}
}
