// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"
	"gladiator/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookShareUpdate is the builder for updating NotebookShare entities.
type NotebookShareUpdate struct {
	config
	hooks    []Hook
	mutation *NotebookShareMutation
}

// Where appends a list predicates to the NotebookShareUpdate builder.
func (nsu *NotebookShareUpdate) Where(ps ...predicate.NotebookShare) *NotebookShareUpdate {
	nsu.mutation.Where(ps...)
	return nsu
}

// SetNotebookID sets the "notebook_id" field.
func (nsu *NotebookShareUpdate) SetNotebookID(u uuid.UUID) *NotebookShareUpdate {
	nsu.mutation.SetNotebookID(u)
	return nsu
}

// SetNillableNotebookID sets the "notebook_id" field if the given value is not nil.
func (nsu *NotebookShareUpdate) SetNillableNotebookID(u *uuid.UUID) *NotebookShareUpdate {
	if u != nil {
		nsu.SetNotebookID(*u)
	}
	return nsu
}

// SetSharedWithUserID sets the "shared_with_user_id" field.
func (nsu *NotebookShareUpdate) SetSharedWithUserID(u uuid.UUID) *NotebookShareUpdate {
	nsu.mutation.SetSharedWithUserID(u)
	return nsu
}

// SetNillableSharedWithUserID sets the "shared_with_user_id" field if the given value is not nil.
func (nsu *NotebookShareUpdate) SetNillableSharedWithUserID(u *uuid.UUID) *NotebookShareUpdate {
	if u != nil {
		nsu.SetSharedWithUserID(*u)
	}
	return nsu
}

// SetPermission sets the "permission" field.
func (nsu *NotebookShareUpdate) SetPermission(n notebookshare.Permission) *NotebookShareUpdate {
	nsu.mutation.SetPermission(n)
	return nsu
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (nsu *NotebookShareUpdate) SetNillablePermission(n *notebookshare.Permission) *NotebookShareUpdate {
	if n != nil {
		nsu.SetPermission(*n)
	}
	return nsu
}

// SetSharedByUserID sets the "shared_by_user_id" field.
func (nsu *NotebookShareUpdate) SetSharedByUserID(u uuid.UUID) *NotebookShareUpdate {
	nsu.mutation.SetSharedByUserID(u)
	return nsu
}

// SetNillableSharedByUserID sets the "shared_by_user_id" field if the given value is not nil.
func (nsu *NotebookShareUpdate) SetNillableSharedByUserID(u *uuid.UUID) *NotebookShareUpdate {
	if u != nil {
		nsu.SetSharedByUserID(*u)
	}
	return nsu
}

// SetNotebook sets the "notebook" edge to the Notebook entity.
func (nsu *NotebookShareUpdate) SetNotebook(n *Notebook) *NotebookShareUpdate {
	return nsu.SetNotebookID(n.ID)
}

// SetSharedWithID sets the "shared_with" edge to the User entity by ID.
func (nsu *NotebookShareUpdate) SetSharedWithID(id uuid.UUID) *NotebookShareUpdate {
	nsu.mutation.SetSharedWithID(id)
	return nsu
}

// SetSharedWith sets the "shared_with" edge to the User entity.
func (nsu *NotebookShareUpdate) SetSharedWith(u *User) *NotebookShareUpdate {
	return nsu.SetSharedWithID(u.ID)
}

// Mutation returns the NotebookShareMutation object of the builder.
func (nsu *NotebookShareUpdate) Mutation() *NotebookShareMutation {
	return nsu.mutation
}

// ClearNotebook clears the "notebook" edge to the Notebook entity.
func (nsu *NotebookShareUpdate) ClearNotebook() *NotebookShareUpdate {
	nsu.mutation.ClearNotebook()
	return nsu
}

// ClearSharedWith clears the "shared_with" edge to the User entity.
func (nsu *NotebookShareUpdate) ClearSharedWith() *NotebookShareUpdate {
	nsu.mutation.ClearSharedWith()
	return nsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nsu *NotebookShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nsu.sqlSave, nsu.mutation, nsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nsu *NotebookShareUpdate) SaveX(ctx context.Context) int {
	affected, err := nsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nsu *NotebookShareUpdate) Exec(ctx context.Context) error {
	_, err := nsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsu *NotebookShareUpdate) ExecX(ctx context.Context) {
	if err := nsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nsu *NotebookShareUpdate) check() error {
	if v, ok := nsu.mutation.Permission(); ok {
		if err := notebookshare.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "NotebookShare.permission": %w`, err)}
		}
	}
	if nsu.mutation.NotebookCleared() && len(nsu.mutation.NotebookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotebookShare.notebook"`)
	}
	if nsu.mutation.SharedWithCleared() && len(nsu.mutation.SharedWithIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotebookShare.shared_with"`)
	}
	return nil
}

func (nsu *NotebookShareUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notebookshare.Table, notebookshare.Columns, sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID))
	if ps := nsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nsu.mutation.Permission(); ok {
		_spec.SetField(notebookshare.FieldPermission, field.TypeEnum, value)
	}
	if value, ok := nsu.mutation.SharedByUserID(); ok {
		_spec.SetField(notebookshare.FieldSharedByUserID, field.TypeUUID, value)
	}
	if nsu.mutation.NotebookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.NotebookTable,
			Columns: []string{notebookshare.NotebookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsu.mutation.NotebookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.NotebookTable,
			Columns: []string{notebookshare.NotebookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nsu.mutation.SharedWithCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.SharedWithTable,
			Columns: []string{notebookshare.SharedWithColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsu.mutation.SharedWithIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.SharedWithTable,
			Columns: []string{notebookshare.SharedWithColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notebookshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nsu.mutation.done = true
	return n, nil
}

// NotebookShareUpdateOne is the builder for updating a single NotebookShare entity.
type NotebookShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotebookShareMutation
}

// SetNotebookID sets the "notebook_id" field.
func (nsuo *NotebookShareUpdateOne) SetNotebookID(u uuid.UUID) *NotebookShareUpdateOne {
	nsuo.mutation.SetNotebookID(u)
	return nsuo
}

// SetNillableNotebookID sets the "notebook_id" field if the given value is not nil.
func (nsuo *NotebookShareUpdateOne) SetNillableNotebookID(u *uuid.UUID) *NotebookShareUpdateOne {
	if u != nil {
		nsuo.SetNotebookID(*u)
	}
	return nsuo
}

// SetSharedWithUserID sets the "shared_with_user_id" field.
func (nsuo *NotebookShareUpdateOne) SetSharedWithUserID(u uuid.UUID) *NotebookShareUpdateOne {
	nsuo.mutation.SetSharedWithUserID(u)
	return nsuo
}

// SetNillableSharedWithUserID sets the "shared_with_user_id" field if the given value is not nil.
func (nsuo *NotebookShareUpdateOne) SetNillableSharedWithUserID(u *uuid.UUID) *NotebookShareUpdateOne {
	if u != nil {
		nsuo.SetSharedWithUserID(*u)
	}
	return nsuo
}

// SetPermission sets the "permission" field.
func (nsuo *NotebookShareUpdateOne) SetPermission(n notebookshare.Permission) *NotebookShareUpdateOne {
	nsuo.mutation.SetPermission(n)
	return nsuo
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (nsuo *NotebookShareUpdateOne) SetNillablePermission(n *notebookshare.Permission) *NotebookShareUpdateOne {
	if n != nil {
		nsuo.SetPermission(*n)
	}
	return nsuo
}

// SetSharedByUserID sets the "shared_by_user_id" field.
func (nsuo *NotebookShareUpdateOne) SetSharedByUserID(u uuid.UUID) *NotebookShareUpdateOne {
	nsuo.mutation.SetSharedByUserID(u)
	return nsuo
}

// SetNillableSharedByUserID sets the "shared_by_user_id" field if the given value is not nil.
func (nsuo *NotebookShareUpdateOne) SetNillableSharedByUserID(u *uuid.UUID) *NotebookShareUpdateOne {
	if u != nil {
		nsuo.SetSharedByUserID(*u)
	}
	return nsuo
}

// SetNotebook sets the "notebook" edge to the Notebook entity.
func (nsuo *NotebookShareUpdateOne) SetNotebook(n *Notebook) *NotebookShareUpdateOne {
	return nsuo.SetNotebookID(n.ID)
}

// SetSharedWithID sets the "shared_with" edge to the User entity by ID.
func (nsuo *NotebookShareUpdateOne) SetSharedWithID(id uuid.UUID) *NotebookShareUpdateOne {
	nsuo.mutation.SetSharedWithID(id)
	return nsuo
}

// SetSharedWith sets the "shared_with" edge to the User entity.
func (nsuo *NotebookShareUpdateOne) SetSharedWith(u *User) *NotebookShareUpdateOne {
	return nsuo.SetSharedWithID(u.ID)
}

// Mutation returns the NotebookShareMutation object of the builder.
func (nsuo *NotebookShareUpdateOne) Mutation() *NotebookShareMutation {
	return nsuo.mutation
}

// ClearNotebook clears the "notebook" edge to the Notebook entity.
func (nsuo *NotebookShareUpdateOne) ClearNotebook() *NotebookShareUpdateOne {
	nsuo.mutation.ClearNotebook()
	return nsuo
}

// ClearSharedWith clears the "shared_with" edge to the User entity.
func (nsuo *NotebookShareUpdateOne) ClearSharedWith() *NotebookShareUpdateOne {
	nsuo.mutation.ClearSharedWith()
	return nsuo
}

// Where appends a list predicates to the NotebookShareUpdate builder.
func (nsuo *NotebookShareUpdateOne) Where(ps ...predicate.NotebookShare) *NotebookShareUpdateOne {
	nsuo.mutation.Where(ps...)
	return nsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nsuo *NotebookShareUpdateOne) Select(field string, fields ...string) *NotebookShareUpdateOne {
	nsuo.fields = append([]string{field}, fields...)
	return nsuo
}

// Save executes the query and returns the updated NotebookShare entity.
func (nsuo *NotebookShareUpdateOne) Save(ctx context.Context) (*NotebookShare, error) {
	return withHooks(ctx, nsuo.sqlSave, nsuo.mutation, nsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nsuo *NotebookShareUpdateOne) SaveX(ctx context.Context) *NotebookShare {
	node, err := nsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nsuo *NotebookShareUpdateOne) Exec(ctx context.Context) error {
	_, err := nsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsuo *NotebookShareUpdateOne) ExecX(ctx context.Context) {
	if err := nsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nsuo *NotebookShareUpdateOne) check() error {
	if v, ok := nsuo.mutation.Permission(); ok {
		if err := notebookshare.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "NotebookShare.permission": %w`, err)}
		}
	}
	if nsuo.mutation.NotebookCleared() && len(nsuo.mutation.NotebookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotebookShare.notebook"`)
	}
	if nsuo.mutation.SharedWithCleared() && len(nsuo.mutation.SharedWithIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotebookShare.shared_with"`)
	}
	return nil
}

func (nsuo *NotebookShareUpdateOne) sqlSave(ctx context.Context) (_node *NotebookShare, err error) {
	if err := nsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notebookshare.Table, notebookshare.Columns, sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID))
	id, ok := nsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotebookShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notebookshare.FieldID)
		for _, f := range fields {
			if !notebookshare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notebookshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nsuo.mutation.Permission(); ok {
		_spec.SetField(notebookshare.FieldPermission, field.TypeEnum, value)
	}
	if value, ok := nsuo.mutation.SharedByUserID(); ok {
		_spec.SetField(notebookshare.FieldSharedByUserID, field.TypeUUID, value)
	}
	if nsuo.mutation.NotebookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.NotebookTable,
			Columns: []string{notebookshare.NotebookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsuo.mutation.NotebookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.NotebookTable,
			Columns: []string{notebookshare.NotebookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nsuo.mutation.SharedWithCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.SharedWithTable,
			Columns: []string{notebookshare.SharedWithColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsuo.mutation.SharedWithIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.SharedWithTable,
			Columns: []string{notebookshare.SharedWithColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotebookShare{config: nsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notebookshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nsuo.mutation.done = true
	return _node, nil
}
