// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Notebook is the model entity for the Notebook schema.
type Notebook struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Content holds the value of the "content" field.
	Content map[string]interface{} `json:"content,omitempty"`
	// IsPublic holds the value of the "is_public" field.
	IsPublic bool `json:"is_public,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastExecutedAt holds the value of the "last_executed_at" field.
	LastExecutedAt *time.Time `json:"last_executed_at,omitempty"`
	// ExecutionCount holds the value of the "execution_count" field.
	ExecutionCount int `json:"execution_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotebookQuery when eager-loading is set.
	Edges        NotebookEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotebookEdges holds the relations/edges for other nodes in the graph.
type NotebookEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Shares holds the value of the shares edge.
	Shares []*NotebookShare `json:"shares,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotebookEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// SharesOrErr returns the Shares value or an error if the edge
// was not loaded in eager-loading.
func (e NotebookEdges) SharesOrErr() ([]*NotebookShare, error) {
	if e.loadedTypes[1] {
		return e.Shares, nil
	}
	return nil, &NotLoadedError{edge: "shares"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notebook) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notebook.FieldContent:
			values[i] = new([]byte)
		case notebook.FieldIsPublic:
			values[i] = new(sql.NullBool)
		case notebook.FieldExecutionCount:
			values[i] = new(sql.NullInt64)
		case notebook.FieldTitle, notebook.FieldDescription:
			values[i] = new(sql.NullString)
		case notebook.FieldCreatedAt, notebook.FieldUpdatedAt, notebook.FieldLastExecutedAt:
			values[i] = new(sql.NullTime)
		case notebook.FieldID, notebook.FieldOwnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notebook fields.
func (n *Notebook) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notebook.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				n.ID = *value
			}
		case notebook.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				n.OwnerID = *value
			}
		case notebook.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				n.Title = value.String
			}
		case notebook.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				n.Description = new(string)
				*n.Description = value.String
			}
		case notebook.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &n.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case notebook.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				n.IsPublic = value.Bool
			}
		case notebook.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				n.CreatedAt = value.Time
			}
		case notebook.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				n.UpdatedAt = value.Time
			}
		case notebook.FieldLastExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_executed_at", values[i])
			} else if value.Valid {
				n.LastExecutedAt = new(time.Time)
				*n.LastExecutedAt = value.Time
			}
		case notebook.FieldExecutionCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_count", values[i])
			} else if value.Valid {
				n.ExecutionCount = int(value.Int64)
			}
		default:
			n.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Notebook.
// This includes values selected through modifiers, order, etc.
func (n *Notebook) Value(name string) (ent.Value, error) {
	return n.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Notebook entity.
func (n *Notebook) QueryOwner() *UserQuery {
	return NewNotebookClient(n.config).QueryOwner(n)
}

// QueryShares queries the "shares" edge of the Notebook entity.
func (n *Notebook) QueryShares() *NotebookShareQuery {
	return NewNotebookClient(n.config).QueryShares(n)
}

// Update returns a builder for updating this Notebook.
// Note that you need to call Notebook.Unwrap() before calling this method if this Notebook
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Notebook) Update() *NotebookUpdateOne {
	return NewNotebookClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Notebook entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Notebook) Unwrap() *Notebook {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notebook is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Notebook) String() string {
	var builder strings.Builder
	builder.WriteString("Notebook(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", n.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(n.Title)
	builder.WriteString(", ")
	if v := n.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", n.Content))
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", n.IsPublic))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(n.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(n.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := n.LastExecutedAt; v != nil {
		builder.WriteString("last_executed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("execution_count=")
	builder.WriteString(fmt.Sprintf("%v", n.ExecutionCount))
	builder.WriteByte(')')
	return builder.String()
}

// Notebooks is a parsable slice of Notebook.
type Notebooks []*Notebook
