// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotebookShareDelete is the builder for deleting a NotebookShare entity.
type NotebookShareDelete struct {
	config
	hooks    []Hook
	mutation *NotebookShareMutation
}

// Where appends a list predicates to the NotebookShareDelete builder.
func (nsd *NotebookShareDelete) Where(ps ...predicate.NotebookShare) *NotebookShareDelete {
	nsd.mutation.Where(ps...)
	return nsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nsd *NotebookShareDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nsd.sqlExec, nsd.mutation, nsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nsd *NotebookShareDelete) ExecX(ctx context.Context) int {
	n, err := nsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nsd *NotebookShareDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notebookshare.Table, sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID))
	if ps := nsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nsd.mutation.done = true
	return affected, err
}

// NotebookShareDeleteOne is the builder for deleting a single NotebookShare entity.
type NotebookShareDeleteOne struct {
	nsd *NotebookShareDelete
}

// Where appends a list predicates to the NotebookShareDelete builder.
func (nsdo *NotebookShareDeleteOne) Where(ps ...predicate.NotebookShare) *NotebookShareDeleteOne {
	nsdo.nsd.mutation.Where(ps...)
	return nsdo
}

// Exec executes the deletion query.
func (nsdo *NotebookShareDeleteOne) Exec(ctx context.Context) error {
	n, err := nsdo.nsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notebookshare.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nsdo *NotebookShareDeleteOne) ExecX(ctx context.Context) {
	if err := nsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
