// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookCreate is the builder for creating a Notebook entity.
type NotebookCreate struct {
	config
	mutation *NotebookMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (nc *NotebookCreate) SetOwnerID(u uuid.UUID) *NotebookCreate {
	nc.mutation.SetOwnerID(u)
	return nc
}

// SetTitle sets the "title" field.
func (nc *NotebookCreate) SetTitle(s string) *NotebookCreate {
	nc.mutation.SetTitle(s)
	return nc
}

// SetDescription sets the "description" field.
func (nc *NotebookCreate) SetDescription(s string) *NotebookCreate {
	nc.mutation.SetDescription(s)
	return nc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableDescription(s *string) *NotebookCreate {
	if s != nil {
		nc.SetDescription(*s)
	}
	return nc
}

// SetContent sets the "content" field.
func (nc *NotebookCreate) SetContent(m map[string]interface{}) *NotebookCreate {
	nc.mutation.SetContent(m)
	return nc
}

// SetIsPublic sets the "is_public" field.
func (nc *NotebookCreate) SetIsPublic(b bool) *NotebookCreate {
	nc.mutation.SetIsPublic(b)
	return nc
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableIsPublic(b *bool) *NotebookCreate {
	if b != nil {
		nc.SetIsPublic(*b)
	}
	return nc
}

// SetCreatedAt sets the "created_at" field.
func (nc *NotebookCreate) SetCreatedAt(t time.Time) *NotebookCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableCreatedAt(t *time.Time) *NotebookCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetUpdatedAt sets the "updated_at" field.
func (nc *NotebookCreate) SetUpdatedAt(t time.Time) *NotebookCreate {
	nc.mutation.SetUpdatedAt(t)
	return nc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableUpdatedAt(t *time.Time) *NotebookCreate {
	if t != nil {
		nc.SetUpdatedAt(*t)
	}
	return nc
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (nc *NotebookCreate) SetLastExecutedAt(t time.Time) *NotebookCreate {
	nc.mutation.SetLastExecutedAt(t)
	return nc
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableLastExecutedAt(t *time.Time) *NotebookCreate {
	if t != nil {
		nc.SetLastExecutedAt(*t)
	}
	return nc
}

// SetExecutionCount sets the "execution_count" field.
func (nc *NotebookCreate) SetExecutionCount(i int) *NotebookCreate {
	nc.mutation.SetExecutionCount(i)
	return nc
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableExecutionCount(i *int) *NotebookCreate {
	if i != nil {
		nc.SetExecutionCount(*i)
	}
	return nc
}

// SetID sets the "id" field.
func (nc *NotebookCreate) SetID(u uuid.UUID) *NotebookCreate {
	nc.mutation.SetID(u)
	return nc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (nc *NotebookCreate) SetNillableID(u *uuid.UUID) *NotebookCreate {
	if u != nil {
		nc.SetID(*u)
	}
	return nc
}

// SetOwner sets the "owner" edge to the User entity.
func (nc *NotebookCreate) SetOwner(u *User) *NotebookCreate {
	return nc.SetOwnerID(u.ID)
}

// AddShareIDs adds the "shares" edge to the NotebookShare entity by IDs.
func (nc *NotebookCreate) AddShareIDs(ids ...uuid.UUID) *NotebookCreate {
	nc.mutation.AddShareIDs(ids...)
	return nc
}

// AddShares adds the "shares" edges to the NotebookShare entity.
func (nc *NotebookCreate) AddShares(n ...*NotebookShare) *NotebookCreate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nc.AddShareIDs(ids...)
}

// Mutation returns the NotebookMutation object of the builder.
func (nc *NotebookCreate) Mutation() *NotebookMutation {
	return nc.mutation
}

// Save creates the Notebook in the database.
func (nc *NotebookCreate) Save(ctx context.Context) (*Notebook, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NotebookCreate) SaveX(ctx context.Context) *Notebook {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NotebookCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NotebookCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NotebookCreate) defaults() {
	if _, ok := nc.mutation.Content(); !ok {
		v := notebook.DefaultContent
		nc.mutation.SetContent(v)
	}
	if _, ok := nc.mutation.IsPublic(); !ok {
		v := notebook.DefaultIsPublic
		nc.mutation.SetIsPublic(v)
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := notebook.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		v := notebook.DefaultUpdatedAt()
		nc.mutation.SetUpdatedAt(v)
	}
	if _, ok := nc.mutation.ExecutionCount(); !ok {
		v := notebook.DefaultExecutionCount
		nc.mutation.SetExecutionCount(v)
	}
	if _, ok := nc.mutation.ID(); !ok {
		v := notebook.DefaultID()
		nc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NotebookCreate) check() error {
	if _, ok := nc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Notebook.owner_id"`)}
	}
	if _, ok := nc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notebook.title"`)}
	}
	if v, ok := nc.mutation.Title(); ok {
		if err := notebook.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notebook.title": %w`, err)}
		}
	}
	if _, ok := nc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Notebook.content"`)}
	}
	if _, ok := nc.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Notebook.is_public"`)}
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notebook.created_at"`)}
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Notebook.updated_at"`)}
	}
	if _, ok := nc.mutation.ExecutionCount(); !ok {
		return &ValidationError{Name: "execution_count", err: errors.New(`ent: missing required field "Notebook.execution_count"`)}
	}
	if v, ok := nc.mutation.ExecutionCount(); ok {
		if err := notebook.ExecutionCountValidator(v); err != nil {
			return &ValidationError{Name: "execution_count", err: fmt.Errorf(`ent: validator failed for field "Notebook.execution_count": %w`, err)}
		}
	}
	if len(nc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Notebook.owner"`)}
	}
	return nil
}

func (nc *NotebookCreate) sqlSave(ctx context.Context) (*Notebook, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NotebookCreate) createSpec() (*Notebook, *sqlgraph.CreateSpec) {
	var (
		_node = &Notebook{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(notebook.Table, sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID))
	)
	if id, ok := nc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := nc.mutation.Title(); ok {
		_spec.SetField(notebook.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := nc.mutation.Description(); ok {
		_spec.SetField(notebook.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := nc.mutation.Content(); ok {
		_spec.SetField(notebook.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := nc.mutation.IsPublic(); ok {
		_spec.SetField(notebook.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.SetField(notebook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := nc.mutation.UpdatedAt(); ok {
		_spec.SetField(notebook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := nc.mutation.LastExecutedAt(); ok {
		_spec.SetField(notebook.FieldLastExecutedAt, field.TypeTime, value)
		_node.LastExecutedAt = &value
	}
	if value, ok := nc.mutation.ExecutionCount(); ok {
		_spec.SetField(notebook.FieldExecutionCount, field.TypeInt, value)
		_node.ExecutionCount = value
	}
	if nodes := nc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebook.OwnerTable,
			Columns: []string{notebook.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notebook.SharesTable,
			Columns: []string{notebook.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotebookCreateBulk is the builder for creating many Notebook entities in bulk.
type NotebookCreateBulk struct {
	config
	err      error
	builders []*NotebookCreate
}

// Save creates the Notebook entities in the database.
func (ncb *NotebookCreateBulk) Save(ctx context.Context) ([]*Notebook, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notebook, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotebookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NotebookCreateBulk) SaveX(ctx context.Context) []*Notebook {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NotebookCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NotebookCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
