// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"
	"gladiator/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookShareQuery is the builder for querying NotebookShare entities.
type NotebookShareQuery struct {
	config
	ctx            *QueryContext
	order          []notebookshare.OrderOption
	inters         []Interceptor
	predicates     []predicate.NotebookShare
	withNotebook   *NotebookQuery
	withSharedWith *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotebookShareQuery builder.
func (nsq *NotebookShareQuery) Where(ps ...predicate.NotebookShare) *NotebookShareQuery {
	nsq.predicates = append(nsq.predicates, ps...)
	return nsq
}

// Limit the number of records to be returned by this query.
func (nsq *NotebookShareQuery) Limit(limit int) *NotebookShareQuery {
	nsq.ctx.Limit = &limit
	return nsq
}

// Offset to start from.
func (nsq *NotebookShareQuery) Offset(offset int) *NotebookShareQuery {
	nsq.ctx.Offset = &offset
	return nsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nsq *NotebookShareQuery) Unique(unique bool) *NotebookShareQuery {
	nsq.ctx.Unique = &unique
	return nsq
}

// Order specifies how the records should be ordered.
func (nsq *NotebookShareQuery) Order(o ...notebookshare.OrderOption) *NotebookShareQuery {
	nsq.order = append(nsq.order, o...)
	return nsq
}

// QueryNotebook chains the current query on the "notebook" edge.
func (nsq *NotebookShareQuery) QueryNotebook() *NotebookQuery {
	query := (&NotebookClient{config: nsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(notebookshare.Table, notebookshare.FieldID, selector),
			sqlgraph.To(notebook.Table, notebook.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebookshare.NotebookTable, notebookshare.NotebookColumn),
		)
		fromU = sqlgraph.SetNeighbors(nsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySharedWith chains the current query on the "shared_with" edge.
func (nsq *NotebookShareQuery) QuerySharedWith() *UserQuery {
	query := (&UserClient{config: nsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(notebookshare.Table, notebookshare.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebookshare.SharedWithTable, notebookshare.SharedWithColumn),
		)
		fromU = sqlgraph.SetNeighbors(nsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NotebookShare entity from the query.
// Returns a *NotFoundError when no NotebookShare was found.
func (nsq *NotebookShareQuery) First(ctx context.Context) (*NotebookShare, error) {
	nodes, err := nsq.Limit(1).All(setContextOp(ctx, nsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notebookshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nsq *NotebookShareQuery) FirstX(ctx context.Context) *NotebookShare {
	node, err := nsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NotebookShare ID from the query.
// Returns a *NotFoundError when no NotebookShare ID was found.
func (nsq *NotebookShareQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nsq.Limit(1).IDs(setContextOp(ctx, nsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notebookshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nsq *NotebookShareQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := nsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NotebookShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NotebookShare entity is found.
// Returns a *NotFoundError when no NotebookShare entities are found.
func (nsq *NotebookShareQuery) Only(ctx context.Context) (*NotebookShare, error) {
	nodes, err := nsq.Limit(2).All(setContextOp(ctx, nsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notebookshare.Label}
	default:
		return nil, &NotSingularError{notebookshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nsq *NotebookShareQuery) OnlyX(ctx context.Context) *NotebookShare {
	node, err := nsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NotebookShare ID in the query.
// Returns a *NotSingularError when more than one NotebookShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (nsq *NotebookShareQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nsq.Limit(2).IDs(setContextOp(ctx, nsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notebookshare.Label}
	default:
		err = &NotSingularError{notebookshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nsq *NotebookShareQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := nsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NotebookShares.
func (nsq *NotebookShareQuery) All(ctx context.Context) ([]*NotebookShare, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryAll)
	if err := nsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NotebookShare, *NotebookShareQuery]()
	return withInterceptors[[]*NotebookShare](ctx, nsq, qr, nsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nsq *NotebookShareQuery) AllX(ctx context.Context) []*NotebookShare {
	nodes, err := nsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NotebookShare IDs.
func (nsq *NotebookShareQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if nsq.ctx.Unique == nil && nsq.path != nil {
		nsq.Unique(true)
	}
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryIDs)
	if err = nsq.Select(notebookshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nsq *NotebookShareQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := nsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nsq *NotebookShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryCount)
	if err := nsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nsq, querierCount[*NotebookShareQuery](), nsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nsq *NotebookShareQuery) CountX(ctx context.Context) int {
	count, err := nsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nsq *NotebookShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryExist)
	switch _, err := nsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nsq *NotebookShareQuery) ExistX(ctx context.Context) bool {
	exist, err := nsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotebookShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nsq *NotebookShareQuery) Clone() *NotebookShareQuery {
	if nsq == nil {
		return nil
	}
	return &NotebookShareQuery{
		config:         nsq.config,
		ctx:            nsq.ctx.Clone(),
		order:          append([]notebookshare.OrderOption{}, nsq.order...),
		inters:         append([]Interceptor{}, nsq.inters...),
		predicates:     append([]predicate.NotebookShare{}, nsq.predicates...),
		withNotebook:   nsq.withNotebook.Clone(),
		withSharedWith: nsq.withSharedWith.Clone(),
		// clone intermediate query.
		sql:  nsq.sql.Clone(),
		path: nsq.path,
	}
}

// WithNotebook tells the query-builder to eager-load the nodes that are connected to
// the "notebook" edge. The optional arguments are used to configure the query builder of the edge.
func (nsq *NotebookShareQuery) WithNotebook(opts ...func(*NotebookQuery)) *NotebookShareQuery {
	query := (&NotebookClient{config: nsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nsq.withNotebook = query
	return nsq
}

// WithSharedWith tells the query-builder to eager-load the nodes that are connected to
// the "shared_with" edge. The optional arguments are used to configure the query builder of the edge.
func (nsq *NotebookShareQuery) WithSharedWith(opts ...func(*UserQuery)) *NotebookShareQuery {
	query := (&UserClient{config: nsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nsq.withSharedWith = query
	return nsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NotebookID uuid.UUID `json:"notebook_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NotebookShare.Query().
//		GroupBy(notebookshare.FieldNotebookID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nsq *NotebookShareQuery) GroupBy(field string, fields ...string) *NotebookShareGroupBy {
	nsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NotebookShareGroupBy{build: nsq}
	grbuild.flds = &nsq.ctx.Fields
	grbuild.label = notebookshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NotebookID uuid.UUID `json:"notebook_id,omitempty"`
//	}
//
//	client.NotebookShare.Query().
//		Select(notebookshare.FieldNotebookID).
//		Scan(ctx, &v)
func (nsq *NotebookShareQuery) Select(fields ...string) *NotebookShareSelect {
	nsq.ctx.Fields = append(nsq.ctx.Fields, fields...)
	sbuild := &NotebookShareSelect{NotebookShareQuery: nsq}
	sbuild.label = notebookshare.Label
	sbuild.flds, sbuild.scan = &nsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NotebookShareSelect configured with the given aggregations.
func (nsq *NotebookShareQuery) Aggregate(fns ...AggregateFunc) *NotebookShareSelect {
	return nsq.Select().Aggregate(fns...)
}

func (nsq *NotebookShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nsq); err != nil {
				return err
			}
		}
	}
	for _, f := range nsq.ctx.Fields {
		if !notebookshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nsq.path != nil {
		prev, err := nsq.path(ctx)
		if err != nil {
			return err
		}
		nsq.sql = prev
	}
	return nil
}

func (nsq *NotebookShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NotebookShare, error) {
	var (
		nodes       = []*NotebookShare{}
		_spec       = nsq.querySpec()
		loadedTypes = [2]bool{
			nsq.withNotebook != nil,
			nsq.withSharedWith != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NotebookShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NotebookShare{config: nsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nsq.withNotebook; query != nil {
		if err := nsq.loadNotebook(ctx, query, nodes, nil,
			func(n *NotebookShare, e *Notebook) { n.Edges.Notebook = e }); err != nil {
			return nil, err
		}
	}
	if query := nsq.withSharedWith; query != nil {
		if err := nsq.loadSharedWith(ctx, query, nodes, nil,
			func(n *NotebookShare, e *User) { n.Edges.SharedWith = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nsq *NotebookShareQuery) loadNotebook(ctx context.Context, query *NotebookQuery, nodes []*NotebookShare, init func(*NotebookShare), assign func(*NotebookShare, *Notebook)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*NotebookShare)
	for i := range nodes {
		fk := nodes[i].NotebookID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(notebook.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "notebook_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (nsq *NotebookShareQuery) loadSharedWith(ctx context.Context, query *UserQuery, nodes []*NotebookShare, init func(*NotebookShare), assign func(*NotebookShare, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*NotebookShare)
	for i := range nodes {
		fk := nodes[i].SharedWithUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shared_with_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nsq *NotebookShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nsq.querySpec()
	_spec.Node.Columns = nsq.ctx.Fields
	if len(nsq.ctx.Fields) > 0 {
		_spec.Unique = nsq.ctx.Unique != nil && *nsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nsq.driver, _spec)
}

func (nsq *NotebookShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(notebookshare.Table, notebookshare.Columns, sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID))
	_spec.From = nsq.sql
	if unique := nsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nsq.path != nil {
		_spec.Unique = true
	}
	if fields := nsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notebookshare.FieldID)
		for i := range fields {
			if fields[i] != notebookshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if nsq.withNotebook != nil {
			_spec.Node.AddColumnOnce(notebookshare.FieldNotebookID)
		}
		if nsq.withSharedWith != nil {
			_spec.Node.AddColumnOnce(notebookshare.FieldSharedWithUserID)
		}
	}
	if ps := nsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nsq *NotebookShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nsq.driver.Dialect())
	t1 := builder.Table(notebookshare.Table)
	columns := nsq.ctx.Fields
	if len(columns) == 0 {
		columns = notebookshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nsq.sql != nil {
		selector = nsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nsq.ctx.Unique != nil && *nsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nsq.predicates {
		p(selector)
	}
	for _, p := range nsq.order {
		p(selector)
	}
	if offset := nsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NotebookShareGroupBy is the group-by builder for NotebookShare entities.
type NotebookShareGroupBy struct {
	selector
	build *NotebookShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nsgb *NotebookShareGroupBy) Aggregate(fns ...AggregateFunc) *NotebookShareGroupBy {
	nsgb.fns = append(nsgb.fns, fns...)
	return nsgb
}

// Scan applies the selector query and scans the result into the given value.
func (nsgb *NotebookShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nsgb.build.ctx, ent.OpQueryGroupBy)
	if err := nsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotebookShareQuery, *NotebookShareGroupBy](ctx, nsgb.build, nsgb, nsgb.build.inters, v)
}

func (nsgb *NotebookShareGroupBy) sqlScan(ctx context.Context, root *NotebookShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nsgb.fns))
	for _, fn := range nsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nsgb.flds)+len(nsgb.fns))
		for _, f := range *nsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NotebookShareSelect is the builder for selecting fields of NotebookShare entities.
type NotebookShareSelect struct {
	*NotebookShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nss *NotebookShareSelect) Aggregate(fns ...AggregateFunc) *NotebookShareSelect {
	nss.fns = append(nss.fns, fns...)
	return nss
}

// Scan applies the selector query and scans the result into the given value.
func (nss *NotebookShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nss.ctx, ent.OpQuerySelect)
	if err := nss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotebookShareQuery, *NotebookShareSelect](ctx, nss.NotebookShareQuery, nss, nss.inters, v)
}

func (nss *NotebookShareSelect) sqlScan(ctx context.Context, root *NotebookShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nss.fns))
	for _, fn := range nss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
