// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/predicate"
	"gladiator/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookQuery is the builder for querying Notebook entities.
type NotebookQuery struct {
	config
	ctx        *QueryContext
	order      []notebook.OrderOption
	inters     []Interceptor
	predicates []predicate.Notebook
	withOwner  *UserQuery
	withShares *NotebookShareQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NotebookQuery builder.
func (nq *NotebookQuery) Where(ps ...predicate.Notebook) *NotebookQuery {
	nq.predicates = append(nq.predicates, ps...)
	return nq
}

// Limit the number of records to be returned by this query.
func (nq *NotebookQuery) Limit(limit int) *NotebookQuery {
	nq.ctx.Limit = &limit
	return nq
}

// Offset to start from.
func (nq *NotebookQuery) Offset(offset int) *NotebookQuery {
	nq.ctx.Offset = &offset
	return nq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nq *NotebookQuery) Unique(unique bool) *NotebookQuery {
	nq.ctx.Unique = &unique
	return nq
}

// Order specifies how the records should be ordered.
func (nq *NotebookQuery) Order(o ...notebook.OrderOption) *NotebookQuery {
	nq.order = append(nq.order, o...)
	return nq
}

// QueryOwner chains the current query on the "owner" edge.
func (nq *NotebookQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: nq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(notebook.Table, notebook.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notebook.OwnerTable, notebook.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(nq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryShares chains the current query on the "shares" edge.
func (nq *NotebookQuery) QueryShares() *NotebookShareQuery {
	query := (&NotebookShareClient{config: nq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(notebook.Table, notebook.FieldID, selector),
			sqlgraph.To(notebookshare.Table, notebookshare.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, notebook.SharesTable, notebook.SharesColumn),
		)
		fromU = sqlgraph.SetNeighbors(nq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Notebook entity from the query.
// Returns a *NotFoundError when no Notebook was found.
func (nq *NotebookQuery) First(ctx context.Context) (*Notebook, error) {
	nodes, err := nq.Limit(1).All(setContextOp(ctx, nq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{notebook.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nq *NotebookQuery) FirstX(ctx context.Context) *Notebook {
	node, err := nq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Notebook ID from the query.
// Returns a *NotFoundError when no Notebook ID was found.
func (nq *NotebookQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nq.Limit(1).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{notebook.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nq *NotebookQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := nq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Notebook entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Notebook entity is found.
// Returns a *NotFoundError when no Notebook entities are found.
func (nq *NotebookQuery) Only(ctx context.Context) (*Notebook, error) {
	nodes, err := nq.Limit(2).All(setContextOp(ctx, nq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{notebook.Label}
	default:
		return nil, &NotSingularError{notebook.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nq *NotebookQuery) OnlyX(ctx context.Context) *Notebook {
	node, err := nq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Notebook ID in the query.
// Returns a *NotSingularError when more than one Notebook ID is found.
// Returns a *NotFoundError when no entities are found.
func (nq *NotebookQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = nq.Limit(2).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{notebook.Label}
	default:
		err = &NotSingularError{notebook.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nq *NotebookQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := nq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Notebooks.
func (nq *NotebookQuery) All(ctx context.Context) ([]*Notebook, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryAll)
	if err := nq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Notebook, *NotebookQuery]()
	return withInterceptors[[]*Notebook](ctx, nq, qr, nq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nq *NotebookQuery) AllX(ctx context.Context) []*Notebook {
	nodes, err := nq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Notebook IDs.
func (nq *NotebookQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if nq.ctx.Unique == nil && nq.path != nil {
		nq.Unique(true)
	}
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryIDs)
	if err = nq.Select(notebook.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nq *NotebookQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := nq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nq *NotebookQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryCount)
	if err := nq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nq, querierCount[*NotebookQuery](), nq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nq *NotebookQuery) CountX(ctx context.Context) int {
	count, err := nq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nq *NotebookQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryExist)
	switch _, err := nq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nq *NotebookQuery) ExistX(ctx context.Context) bool {
	exist, err := nq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NotebookQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nq *NotebookQuery) Clone() *NotebookQuery {
	if nq == nil {
		return nil
	}
	return &NotebookQuery{
		config:     nq.config,
		ctx:        nq.ctx.Clone(),
		order:      append([]notebook.OrderOption{}, nq.order...),
		inters:     append([]Interceptor{}, nq.inters...),
		predicates: append([]predicate.Notebook{}, nq.predicates...),
		withOwner:  nq.withOwner.Clone(),
		withShares: nq.withShares.Clone(),
		// clone intermediate query.
		sql:  nq.sql.Clone(),
		path: nq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (nq *NotebookQuery) WithOwner(opts ...func(*UserQuery)) *NotebookQuery {
	query := (&UserClient{config: nq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nq.withOwner = query
	return nq
}

// WithShares tells the query-builder to eager-load the nodes that are connected to
// the "shares" edge. The optional arguments are used to configure the query builder of the edge.
func (nq *NotebookQuery) WithShares(opts ...func(*NotebookShareQuery)) *NotebookQuery {
	query := (&NotebookShareClient{config: nq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nq.withShares = query
	return nq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Notebook.Query().
//		GroupBy(notebook.FieldOwnerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nq *NotebookQuery) GroupBy(field string, fields ...string) *NotebookGroupBy {
	nq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NotebookGroupBy{build: nq}
	grbuild.flds = &nq.ctx.Fields
	grbuild.label = notebook.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//	}
//
//	client.Notebook.Query().
//		Select(notebook.FieldOwnerID).
//		Scan(ctx, &v)
func (nq *NotebookQuery) Select(fields ...string) *NotebookSelect {
	nq.ctx.Fields = append(nq.ctx.Fields, fields...)
	sbuild := &NotebookSelect{NotebookQuery: nq}
	sbuild.label = notebook.Label
	sbuild.flds, sbuild.scan = &nq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NotebookSelect configured with the given aggregations.
func (nq *NotebookQuery) Aggregate(fns ...AggregateFunc) *NotebookSelect {
	return nq.Select().Aggregate(fns...)
}

func (nq *NotebookQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nq); err != nil {
				return err
			}
		}
	}
	for _, f := range nq.ctx.Fields {
		if !notebook.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nq.path != nil {
		prev, err := nq.path(ctx)
		if err != nil {
			return err
		}
		nq.sql = prev
	}
	return nil
}

func (nq *NotebookQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Notebook, error) {
	var (
		nodes       = []*Notebook{}
		_spec       = nq.querySpec()
		loadedTypes = [2]bool{
			nq.withOwner != nil,
			nq.withShares != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Notebook).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Notebook{config: nq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nq.withOwner; query != nil {
		if err := nq.loadOwner(ctx, query, nodes, nil,
			func(n *Notebook, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := nq.withShares; query != nil {
		if err := nq.loadShares(ctx, query, nodes,
			func(n *Notebook) { n.Edges.Shares = []*NotebookShare{} },
			func(n *Notebook, e *NotebookShare) { n.Edges.Shares = append(n.Edges.Shares, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nq *NotebookQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Notebook, init func(*Notebook), assign func(*Notebook, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Notebook)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (nq *NotebookQuery) loadShares(ctx context.Context, query *NotebookShareQuery, nodes []*Notebook, init func(*Notebook), assign func(*Notebook, *NotebookShare)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Notebook)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notebookshare.FieldNotebookID)
	}
	query.Where(predicate.NotebookShare(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(notebook.SharesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NotebookID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "notebook_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (nq *NotebookQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nq.querySpec()
	_spec.Node.Columns = nq.ctx.Fields
	if len(nq.ctx.Fields) > 0 {
		_spec.Unique = nq.ctx.Unique != nil && *nq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nq.driver, _spec)
}

func (nq *NotebookQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(notebook.Table, notebook.Columns, sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID))
	_spec.From = nq.sql
	if unique := nq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nq.path != nil {
		_spec.Unique = true
	}
	if fields := nq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notebook.FieldID)
		for i := range fields {
			if fields[i] != notebook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if nq.withOwner != nil {
			_spec.Node.AddColumnOnce(notebook.FieldOwnerID)
		}
	}
	if ps := nq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nq *NotebookQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nq.driver.Dialect())
	t1 := builder.Table(notebook.Table)
	columns := nq.ctx.Fields
	if len(columns) == 0 {
		columns = notebook.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nq.sql != nil {
		selector = nq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nq.ctx.Unique != nil && *nq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nq.predicates {
		p(selector)
	}
	for _, p := range nq.order {
		p(selector)
	}
	if offset := nq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NotebookGroupBy is the group-by builder for Notebook entities.
type NotebookGroupBy struct {
	selector
	build *NotebookQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ngb *NotebookGroupBy) Aggregate(fns ...AggregateFunc) *NotebookGroupBy {
	ngb.fns = append(ngb.fns, fns...)
	return ngb
}

// Scan applies the selector query and scans the result into the given value.
func (ngb *NotebookGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ngb.build.ctx, ent.OpQueryGroupBy)
	if err := ngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotebookQuery, *NotebookGroupBy](ctx, ngb.build, ngb, ngb.build.inters, v)
}

func (ngb *NotebookGroupBy) sqlScan(ctx context.Context, root *NotebookQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ngb.fns))
	for _, fn := range ngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ngb.flds)+len(ngb.fns))
		for _, f := range *ngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NotebookSelect is the builder for selecting fields of Notebook entities.
type NotebookSelect struct {
	*NotebookQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ns *NotebookSelect) Aggregate(fns ...AggregateFunc) *NotebookSelect {
	ns.fns = append(ns.fns, fns...)
	return ns
}

// Scan applies the selector query and scans the result into the given value.
func (ns *NotebookSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ns.ctx, ent.OpQuerySelect)
	if err := ns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NotebookQuery, *NotebookSelect](ctx, ns.NotebookQuery, ns, ns.inters, v)
}

func (ns *NotebookSelect) sqlScan(ctx context.Context, root *NotebookQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ns.fns))
	for _, fn := range ns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
