// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotebookShareCreate is the builder for creating a NotebookShare entity.
type NotebookShareCreate struct {
	config
	mutation *NotebookShareMutation
	hooks    []Hook
}

// SetNotebookID sets the "notebook_id" field.
func (nsc *NotebookShareCreate) SetNotebookID(u uuid.UUID) *NotebookShareCreate {
	nsc.mutation.SetNotebookID(u)
	return nsc
}

// SetSharedWithUserID sets the "shared_with_user_id" field.
func (nsc *NotebookShareCreate) SetSharedWithUserID(u uuid.UUID) *NotebookShareCreate {
	nsc.mutation.SetSharedWithUserID(u)
	return nsc
}

// SetPermission sets the "permission" field.
func (nsc *NotebookShareCreate) SetPermission(n notebookshare.Permission) *NotebookShareCreate {
	nsc.mutation.SetPermission(n)
	return nsc
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (nsc *NotebookShareCreate) SetNillablePermission(n *notebookshare.Permission) *NotebookShareCreate {
	if n != nil {
		nsc.SetPermission(*n)
	}
	return nsc
}

// SetSharedByUserID sets the "shared_by_user_id" field.
func (nsc *NotebookShareCreate) SetSharedByUserID(u uuid.UUID) *NotebookShareCreate {
	nsc.mutation.SetSharedByUserID(u)
	return nsc
}

// SetCreatedAt sets the "created_at" field.
func (nsc *NotebookShareCreate) SetCreatedAt(t time.Time) *NotebookShareCreate {
	nsc.mutation.SetCreatedAt(t)
	return nsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nsc *NotebookShareCreate) SetNillableCreatedAt(t *time.Time) *NotebookShareCreate {
	if t != nil {
		nsc.SetCreatedAt(*t)
	}
	return nsc
}

// SetID sets the "id" field.
func (nsc *NotebookShareCreate) SetID(u uuid.UUID) *NotebookShareCreate {
	nsc.mutation.SetID(u)
	return nsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (nsc *NotebookShareCreate) SetNillableID(u *uuid.UUID) *NotebookShareCreate {
	if u != nil {
		nsc.SetID(*u)
	}
	return nsc
}

// SetNotebook sets the "notebook" edge to the Notebook entity.
func (nsc *NotebookShareCreate) SetNotebook(n *Notebook) *NotebookShareCreate {
	return nsc.SetNotebookID(n.ID)
}

// SetSharedWithID sets the "shared_with" edge to the User entity by ID.
func (nsc *NotebookShareCreate) SetSharedWithID(id uuid.UUID) *NotebookShareCreate {
	nsc.mutation.SetSharedWithID(id)
	return nsc
}

// SetSharedWith sets the "shared_with" edge to the User entity.
func (nsc *NotebookShareCreate) SetSharedWith(u *User) *NotebookShareCreate {
	return nsc.SetSharedWithID(u.ID)
}

// Mutation returns the NotebookShareMutation object of the builder.
func (nsc *NotebookShareCreate) Mutation() *NotebookShareMutation {
	return nsc.mutation
}

// Save creates the NotebookShare in the database.
func (nsc *NotebookShareCreate) Save(ctx context.Context) (*NotebookShare, error) {
	nsc.defaults()
	return withHooks(ctx, nsc.sqlSave, nsc.mutation, nsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nsc *NotebookShareCreate) SaveX(ctx context.Context) *NotebookShare {
	v, err := nsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nsc *NotebookShareCreate) Exec(ctx context.Context) error {
	_, err := nsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsc *NotebookShareCreate) ExecX(ctx context.Context) {
	if err := nsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nsc *NotebookShareCreate) defaults() {
	if _, ok := nsc.mutation.Permission(); !ok {
		v := notebookshare.DefaultPermission
		nsc.mutation.SetPermission(v)
	}
	if _, ok := nsc.mutation.CreatedAt(); !ok {
		v := notebookshare.DefaultCreatedAt()
		nsc.mutation.SetCreatedAt(v)
	}
	if _, ok := nsc.mutation.ID(); !ok {
		v := notebookshare.DefaultID()
		nsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nsc *NotebookShareCreate) check() error {
	if _, ok := nsc.mutation.NotebookID(); !ok {
		return &ValidationError{Name: "notebook_id", err: errors.New(`ent: missing required field "NotebookShare.notebook_id"`)}
	}
	if _, ok := nsc.mutation.SharedWithUserID(); !ok {
		return &ValidationError{Name: "shared_with_user_id", err: errors.New(`ent: missing required field "NotebookShare.shared_with_user_id"`)}
	}
	if _, ok := nsc.mutation.Permission(); !ok {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required field "NotebookShare.permission"`)}
	}
	if v, ok := nsc.mutation.Permission(); ok {
		if err := notebookshare.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "NotebookShare.permission": %w`, err)}
		}
	}
	if _, ok := nsc.mutation.SharedByUserID(); !ok {
		return &ValidationError{Name: "shared_by_user_id", err: errors.New(`ent: missing required field "NotebookShare.shared_by_user_id"`)}
	}
	if _, ok := nsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotebookShare.created_at"`)}
	}
	if len(nsc.mutation.NotebookIDs()) == 0 {
		return &ValidationError{Name: "notebook", err: errors.New(`ent: missing required edge "NotebookShare.notebook"`)}
	}
	if len(nsc.mutation.SharedWithIDs()) == 0 {
		return &ValidationError{Name: "shared_with", err: errors.New(`ent: missing required edge "NotebookShare.shared_with"`)}
	}
	return nil
}

func (nsc *NotebookShareCreate) sqlSave(ctx context.Context) (*NotebookShare, error) {
	if err := nsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	nsc.mutation.id = &_node.ID
	nsc.mutation.done = true
	return _node, nil
}

func (nsc *NotebookShareCreate) createSpec() (*NotebookShare, *sqlgraph.CreateSpec) {
	var (
		_node = &NotebookShare{config: nsc.config}
		_spec = sqlgraph.NewCreateSpec(notebookshare.Table, sqlgraph.NewFieldSpec(notebookshare.FieldID, field.TypeUUID))
	)
	if id, ok := nsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := nsc.mutation.Permission(); ok {
		_spec.SetField(notebookshare.FieldPermission, field.TypeEnum, value)
		_node.Permission = value
	}
	if value, ok := nsc.mutation.SharedByUserID(); ok {
		_spec.SetField(notebookshare.FieldSharedByUserID, field.TypeUUID, value)
		_node.SharedByUserID = value
	}
	if value, ok := nsc.mutation.CreatedAt(); ok {
		_spec.SetField(notebookshare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := nsc.mutation.NotebookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.NotebookTable,
			Columns: []string{notebookshare.NotebookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notebook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotebookID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nsc.mutation.SharedWithIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notebookshare.SharedWithTable,
			Columns: []string{notebookshare.SharedWithColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SharedWithUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotebookShareCreateBulk is the builder for creating many NotebookShare entities in bulk.
type NotebookShareCreateBulk struct {
	config
	err      error
	builders []*NotebookShareCreate
}

// Save creates the NotebookShare entities in the database.
func (nscb *NotebookShareCreateBulk) Save(ctx context.Context) ([]*NotebookShare, error) {
	if nscb.err != nil {
		return nil, nscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nscb.builders))
	nodes := make([]*NotebookShare, len(nscb.builders))
	mutators := make([]Mutator, len(nscb.builders))
	for i := range nscb.builders {
		func(i int, root context.Context) {
			builder := nscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotebookShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nscb *NotebookShareCreateBulk) SaveX(ctx context.Context) []*NotebookShare {
	v, err := nscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nscb *NotebookShareCreateBulk) Exec(ctx context.Context) error {
	_, err := nscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nscb *NotebookShareCreateBulk) ExecX(ctx context.Context) {
	if err := nscb.Exec(ctx); err != nil {
		panic(err)
	}
}
