// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gladiator/ent/notebook"
	"gladiator/ent/notebookshare"
	"gladiator/ent/schema"
	"gladiator/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notebookFields := schema.Notebook{}.Fields()
	_ = notebookFields
	// notebookDescTitle is the schema descriptor for title field.
	notebookDescTitle := notebookFields[2].Descriptor()
	// notebook.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notebook.TitleValidator = func() func(string) error {
		validators := notebookDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// notebookDescContent is the schema descriptor for content field.
	notebookDescContent := notebookFields[4].Descriptor()
	// notebook.DefaultContent holds the default value on creation for the content field.
	notebook.DefaultContent = notebookDescContent.Default.(map[string]interface{})
	// notebookDescIsPublic is the schema descriptor for is_public field.
	notebookDescIsPublic := notebookFields[5].Descriptor()
	// notebook.DefaultIsPublic holds the default value on creation for the is_public field.
	notebook.DefaultIsPublic = notebookDescIsPublic.Default.(bool)
	// notebookDescCreatedAt is the schema descriptor for created_at field.
	notebookDescCreatedAt := notebookFields[6].Descriptor()
	// notebook.DefaultCreatedAt holds the default value on creation for the created_at field.
	notebook.DefaultCreatedAt = notebookDescCreatedAt.Default.(func() time.Time)
	// notebookDescUpdatedAt is the schema descriptor for updated_at field.
	notebookDescUpdatedAt := notebookFields[7].Descriptor()
	// notebook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notebook.DefaultUpdatedAt = notebookDescUpdatedAt.Default.(func() time.Time)
	// notebook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notebook.UpdateDefaultUpdatedAt = notebookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notebookDescExecutionCount is the schema descriptor for execution_count field.
	notebookDescExecutionCount := notebookFields[9].Descriptor()
	// notebook.DefaultExecutionCount holds the default value on creation for the execution_count field.
	notebook.DefaultExecutionCount = notebookDescExecutionCount.Default.(int)
	// notebook.ExecutionCountValidator is a validator for the "execution_count" field. It is called by the builders before save.
	notebook.ExecutionCountValidator = notebookDescExecutionCount.Validators[0].(func(int) error)
	// notebookDescID is the schema descriptor for id field.
	notebookDescID := notebookFields[0].Descriptor()
	// notebook.DefaultID holds the default value on creation for the id field.
	notebook.DefaultID = notebookDescID.Default.(func() uuid.UUID)
	notebookshareFields := schema.NotebookShare{}.Fields()
	_ = notebookshareFields
	// notebookshareDescCreatedAt is the schema descriptor for created_at field.
	notebookshareDescCreatedAt := notebookshareFields[5].Descriptor()
	// notebookshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	notebookshare.DefaultCreatedAt = notebookshareDescCreatedAt.Default.(func() time.Time)
	// notebookshareDescID is the schema descriptor for id field.
	notebookshareDescID := notebookshareFields[0].Descriptor()
	// notebookshare.DefaultID holds the default value on creation for the id field.
	notebookshare.DefaultID = notebookshareDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[4].Descriptor()
	// user.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	user.AvatarURLValidator = userDescAvatarURL.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[8].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
