// Code generated by ent, DO NOT EDIT.

package notebook

import (
	"gladiator/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldOwnerID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldDescription, v))
}

// IsPublic applies equality check predicate on the "is_public" field. It's identical to IsPublicEQ.
func IsPublic(v bool) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldIsPublic, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastExecutedAt applies equality check predicate on the "last_executed_at" field. It's identical to LastExecutedAtEQ.
func LastExecutedAt(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldLastExecutedAt, v))
}

// ExecutionCount applies equality check predicate on the "execution_count" field. It's identical to ExecutionCountEQ.
func ExecutionCount(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldExecutionCount, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldOwnerID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Notebook {
	return predicate.Notebook(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Notebook {
	return predicate.Notebook(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Notebook {
	return predicate.Notebook(sql.FieldContainsFold(FieldDescription, v))
}

// IsPublicEQ applies the EQ predicate on the "is_public" field.
func IsPublicEQ(v bool) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldIsPublic, v))
}

// IsPublicNEQ applies the NEQ predicate on the "is_public" field.
func IsPublicNEQ(v bool) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldIsPublic, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastExecutedAtEQ applies the EQ predicate on the "last_executed_at" field.
func LastExecutedAtEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldLastExecutedAt, v))
}

// LastExecutedAtNEQ applies the NEQ predicate on the "last_executed_at" field.
func LastExecutedAtNEQ(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldLastExecutedAt, v))
}

// LastExecutedAtIn applies the In predicate on the "last_executed_at" field.
func LastExecutedAtIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldLastExecutedAt, vs...))
}

// LastExecutedAtNotIn applies the NotIn predicate on the "last_executed_at" field.
func LastExecutedAtNotIn(vs ...time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldLastExecutedAt, vs...))
}

// LastExecutedAtGT applies the GT predicate on the "last_executed_at" field.
func LastExecutedAtGT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldLastExecutedAt, v))
}

// LastExecutedAtGTE applies the GTE predicate on the "last_executed_at" field.
func LastExecutedAtGTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldLastExecutedAt, v))
}

// LastExecutedAtLT applies the LT predicate on the "last_executed_at" field.
func LastExecutedAtLT(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldLastExecutedAt, v))
}

// LastExecutedAtLTE applies the LTE predicate on the "last_executed_at" field.
func LastExecutedAtLTE(v time.Time) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldLastExecutedAt, v))
}

// LastExecutedAtIsNil applies the IsNil predicate on the "last_executed_at" field.
func LastExecutedAtIsNil() predicate.Notebook {
	return predicate.Notebook(sql.FieldIsNull(FieldLastExecutedAt))
}

// LastExecutedAtNotNil applies the NotNil predicate on the "last_executed_at" field.
func LastExecutedAtNotNil() predicate.Notebook {
	return predicate.Notebook(sql.FieldNotNull(FieldLastExecutedAt))
}

// ExecutionCountEQ applies the EQ predicate on the "execution_count" field.
func ExecutionCountEQ(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldEQ(FieldExecutionCount, v))
}

// ExecutionCountNEQ applies the NEQ predicate on the "execution_count" field.
func ExecutionCountNEQ(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldNEQ(FieldExecutionCount, v))
}

// ExecutionCountIn applies the In predicate on the "execution_count" field.
func ExecutionCountIn(vs ...int) predicate.Notebook {
	return predicate.Notebook(sql.FieldIn(FieldExecutionCount, vs...))
}

// ExecutionCountNotIn applies the NotIn predicate on the "execution_count" field.
func ExecutionCountNotIn(vs ...int) predicate.Notebook {
	return predicate.Notebook(sql.FieldNotIn(FieldExecutionCount, vs...))
}

// ExecutionCountGT applies the GT predicate on the "execution_count" field.
func ExecutionCountGT(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldGT(FieldExecutionCount, v))
}

// ExecutionCountGTE applies the GTE predicate on the "execution_count" field.
func ExecutionCountGTE(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldGTE(FieldExecutionCount, v))
}

// ExecutionCountLT applies the LT predicate on the "execution_count" field.
func ExecutionCountLT(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldLT(FieldExecutionCount, v))
}

// ExecutionCountLTE applies the LTE predicate on the "execution_count" field.
func ExecutionCountLTE(v int) predicate.Notebook {
	return predicate.Notebook(sql.FieldLTE(FieldExecutionCount, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Notebook {
	return predicate.Notebook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Notebook {
	return predicate.Notebook(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShares applies the HasEdge predicate on the "shares" edge.
func HasShares() predicate.Notebook {
	return predicate.Notebook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SharesTable, SharesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSharesWith applies the HasEdge predicate on the "shares" edge with a given conditions (other predicates).
func HasSharesWith(preds ...predicate.NotebookShare) predicate.Notebook {
	return predicate.Notebook(func(s *sql.Selector) {
		step := newSharesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Notebook) predicate.Notebook {
	return predicate.Notebook(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Notebook) predicate.Notebook {
	return predicate.Notebook(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Notebook) predicate.Notebook {
	return predicate.Notebook(sql.NotPredicates(p))
}
