// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Notebook is the predicate function for notebook builders.
type Notebook func(*sql.Selector)

// NotebookShare is the predicate function for notebookshare builders.
type NotebookShare func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
